[2016-11-03 14:00:59] production.ERROR: exception 'ReflectionException' with message 'Class App\Controllers\Authorize does not exist' in /var/www/html/trust/system/Container/Container.php:507
Stack trace:
#0 /var/www/html/trust/system/Container/Container.php(507): ReflectionClass->__construct('App\\Controllers...')
#1 /var/www/html/trust/system/Container/Container.php(431): Container\Container->build('App\\Controllers...', Array)
#2 /var/www/html/trust/system/Foundation/Application.php(443): Container\Container->make('App\\Controllers...', Array)
#3 /var/www/html/trust/system/Routing/ControllerDispatcher.php(76): Foundation\Application->make('App\\Controllers...')
#4 /var/www/html/trust/system/Routing/ControllerDispatcher.php(52): Routing\ControllerDispatcher->makeController('App\\Controllers...')
#5 /var/www/html/trust/system/Routing/Router.php(958): Routing\ControllerDispatcher->dispatch(Object(Routing\Route), Object(Http\Request), 'App\\Controllers...', 'login')
#6 [internal function]: Routing\Router->Routing\{closure}()
#7 /var/www/html/trust/system/Routing/Route.php(128): call_user_func_array(Object(Closure), Array)
#8 /var/www/html/trust/system/Routing/Router.php(1026): Routing\Route->run()
#9 /var/www/html/trust/system/Routing/Router.php(994): Routing\Router->dispatchToRoute(Object(Http\Request))
#10 /var/www/html/trust/system/Foundation/Application.php(744): Routing\Router->dispatch(Object(Http\Request))
#11 /var/www/html/trust/system/Foundation/Application.php(717): Foundation\Application->dispatch(Object(Http\Request))
#12 /var/www/html/trust/shared/Http/ContentGuard.php(62): Foundation\Application->handle(Object(Http\Request), 1, true)
#13 /var/www/html/trust/system/Session/Middleware.php(77): Shared\Http\ContentGuard->handle(Object(Http\Request), 1, true)
#14 /var/www/html/trust/system/Cookie/Queue.php(49): Session\Middleware->handle(Object(Http\Request), 1, true)
#15 /var/www/html/trust/system/Cookie/Guard.php(54): Cookie\Queue->handle(Object(Http\Request), 1, true)
#16 /var/www/html/trust/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Cookie\Guard->handle(Object(Http\Request), 1, true)
#17 /var/www/html/trust/system/Foundation/Application.php(615): Stack\StackedHttpKernel->handle(Object(Http\Request))
#18 /var/www/html/trust/app/Boot/Start.php(244): Foundation\Application->run()
#19 /var/www/html/trust/public/index.php(37): require('/var/www/html/t...')
#20 {main} [] []
[2016-11-03 14:01:10] production.ERROR: exception 'InvalidArgumentException' with message 'Unable to load the view 'Admin/Authorize/Login' on domain 'App'.' in /var/www/html/trust/system/View/Factory.php:280
Stack trace:
#0 /var/www/html/trust/system/View/Factory.php(76): View\Factory->find('Admin/Authorize...', NULL)
#1 [internal function]: View\Factory->make('Admin/Authorize...', Array)
#2 /var/www/html/trust/system/Support/Facades/Facade.php(111): call_user_func_array(Array, Array)
#3 /var/www/html/trust/app/Core/Controller.php(99): Support\Facades\Facade::__callStatic('make', Array)
#4 /var/www/html/trust/app/Core/Controller.php(99): Support\Facades\View::make('Admin/Authorize...', Array)
#5 /var/www/html/trust/app/Controllers/Admin/Authorize.php(37): App\Core\Controller->getView()
#6 [internal function]: App\Controllers\Admin\Authorize->login()
#7 /var/www/html/trust/system/Routing/Controller.php(240): call_user_func_array(Array, Array)
#8 /var/www/html/trust/system/Routing/ControllerDispatcher.php(91): Routing\Controller->callAction('login', Array)
#9 /var/www/html/trust/system/Routing/ControllerDispatcher.php(60): Routing\ControllerDispatcher->call(Object(App\Controllers\Admin\Authorize), Object(Routing\Route), 'login')
#10 /var/www/html/trust/system/Routing/Router.php(958): Routing\ControllerDispatcher->dispatch(Object(Routing\Route), Object(Http\Request), 'App\\Controllers...', 'login')
#11 [internal function]: Routing\Router->Routing\{closure}()
#12 /var/www/html/trust/system/Routing/Route.php(128): call_user_func_array(Object(Closure), Array)
#13 /var/www/html/trust/system/Routing/Router.php(1026): Routing\Route->run()
#14 /var/www/html/trust/system/Routing/Router.php(994): Routing\Router->dispatchToRoute(Object(Http\Request))
#15 /var/www/html/trust/system/Foundation/Application.php(744): Routing\Router->dispatch(Object(Http\Request))
#16 /var/www/html/trust/system/Foundation/Application.php(717): Foundation\Application->dispatch(Object(Http\Request))
#17 /var/www/html/trust/shared/Http/ContentGuard.php(62): Foundation\Application->handle(Object(Http\Request), 1, true)
#18 /var/www/html/trust/system/Session/Middleware.php(77): Shared\Http\ContentGuard->handle(Object(Http\Request), 1, true)
#19 /var/www/html/trust/system/Cookie/Queue.php(49): Session\Middleware->handle(Object(Http\Request), 1, true)
#20 /var/www/html/trust/system/Cookie/Guard.php(54): Cookie\Queue->handle(Object(Http\Request), 1, true)
#21 /var/www/html/trust/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Cookie\Guard->handle(Object(Http\Request), 1, true)
#22 /var/www/html/trust/system/Foundation/Application.php(615): Stack\StackedHttpKernel->handle(Object(Http\Request))
#23 /var/www/html/trust/app/Boot/Start.php(244): Foundation\Application->run()
#24 /var/www/html/trust/public/index.php(37): require('/var/www/html/t...')
#25 {main} [] []
[2016-11-03 14:02:14] production.ERROR: exception 'ReflectionException' with message 'Class App\Controllers\Admin\Dashboard does not exist' in /var/www/html/trust/system/Container/Container.php:507
Stack trace:
#0 /var/www/html/trust/system/Container/Container.php(507): ReflectionClass->__construct('App\\Controllers...')
#1 /var/www/html/trust/system/Container/Container.php(431): Container\Container->build('App\\Controllers...', Array)
#2 /var/www/html/trust/system/Foundation/Application.php(443): Container\Container->make('App\\Controllers...', Array)
#3 /var/www/html/trust/system/Routing/ControllerDispatcher.php(76): Foundation\Application->make('App\\Controllers...')
#4 /var/www/html/trust/system/Routing/ControllerDispatcher.php(52): Routing\ControllerDispatcher->makeController('App\\Controllers...')
#5 /var/www/html/trust/system/Routing/Router.php(958): Routing\ControllerDispatcher->dispatch(Object(Routing\Route), Object(Http\Request), 'App\\Controllers...', 'index')
#6 [internal function]: Routing\Router->Routing\{closure}()
#7 /var/www/html/trust/system/Routing/Route.php(128): call_user_func_array(Object(Closure), Array)
#8 /var/www/html/trust/system/Routing/Router.php(1026): Routing\Route->run()
#9 /var/www/html/trust/system/Routing/Router.php(994): Routing\Router->dispatchToRoute(Object(Http\Request))
#10 /var/www/html/trust/system/Foundation/Application.php(744): Routing\Router->dispatch(Object(Http\Request))
#11 /var/www/html/trust/system/Foundation/Application.php(717): Foundation\Application->dispatch(Object(Http\Request))
#12 /var/www/html/trust/shared/Http/ContentGuard.php(62): Foundation\Application->handle(Object(Http\Request), 1, true)
#13 /var/www/html/trust/system/Session/Middleware.php(77): Shared\Http\ContentGuard->handle(Object(Http\Request), 1, true)
#14 /var/www/html/trust/system/Cookie/Queue.php(49): Session\Middleware->handle(Object(Http\Request), 1, true)
#15 /var/www/html/trust/system/Cookie/Guard.php(54): Cookie\Queue->handle(Object(Http\Request), 1, true)
#16 /var/www/html/trust/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Cookie\Guard->handle(Object(Http\Request), 1, true)
#17 /var/www/html/trust/system/Foundation/Application.php(615): Stack\StackedHttpKernel->handle(Object(Http\Request))
#18 /var/www/html/trust/app/Boot/Start.php(244): Foundation\Application->run()
#19 /var/www/html/trust/public/index.php(37): require('/var/www/html/t...')
#20 {main} [] []
[2016-11-03 14:04:33] production.ERROR: exception 'InvalidArgumentException' with message 'Unable to load the view 'Admin/Dashboard/Index' on domain 'App'.' in /var/www/html/trust/system/View/Factory.php:280
Stack trace:
#0 /var/www/html/trust/system/View/Factory.php(76): View\Factory->find('Admin/Dashboard...', NULL)
#1 [internal function]: View\Factory->make('Admin/Dashboard...', Array)
#2 /var/www/html/trust/system/Support/Facades/Facade.php(111): call_user_func_array(Array, Array)
#3 /var/www/html/trust/app/Core/Controller.php(99): Support\Facades\Facade::__callStatic('make', Array)
#4 /var/www/html/trust/app/Core/Controller.php(99): Support\Facades\View::make('Admin/Dashboard...', Array)
#5 /var/www/html/trust/app/Controllers/Admin/Dashboard.php(21): App\Core\Controller->getView()
#6 [internal function]: App\Controllers\Admin\Dashboard->index()
#7 /var/www/html/trust/system/Routing/Controller.php(240): call_user_func_array(Array, Array)
#8 /var/www/html/trust/system/Routing/ControllerDispatcher.php(91): Routing\Controller->callAction('index', Array)
#9 /var/www/html/trust/system/Routing/ControllerDispatcher.php(60): Routing\ControllerDispatcher->call(Object(App\Controllers\Admin\Dashboard), Object(Routing\Route), 'index')
#10 /var/www/html/trust/system/Routing/Router.php(958): Routing\ControllerDispatcher->dispatch(Object(Routing\Route), Object(Http\Request), 'App\\Controllers...', 'index')
#11 [internal function]: Routing\Router->Routing\{closure}()
#12 /var/www/html/trust/system/Routing/Route.php(128): call_user_func_array(Object(Closure), Array)
#13 /var/www/html/trust/system/Routing/Router.php(1026): Routing\Route->run()
#14 /var/www/html/trust/system/Routing/Router.php(994): Routing\Router->dispatchToRoute(Object(Http\Request))
#15 /var/www/html/trust/system/Foundation/Application.php(744): Routing\Router->dispatch(Object(Http\Request))
#16 /var/www/html/trust/system/Foundation/Application.php(717): Foundation\Application->dispatch(Object(Http\Request))
#17 /var/www/html/trust/shared/Http/ContentGuard.php(62): Foundation\Application->handle(Object(Http\Request), 1, true)
#18 /var/www/html/trust/system/Session/Middleware.php(77): Shared\Http\ContentGuard->handle(Object(Http\Request), 1, true)
#19 /var/www/html/trust/system/Cookie/Queue.php(49): Session\Middleware->handle(Object(Http\Request), 1, true)
#20 /var/www/html/trust/system/Cookie/Guard.php(54): Cookie\Queue->handle(Object(Http\Request), 1, true)
#21 /var/www/html/trust/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Cookie\Guard->handle(Object(Http\Request), 1, true)
#22 /var/www/html/trust/system/Foundation/Application.php(615): Stack\StackedHttpKernel->handle(Object(Http\Request))
#23 /var/www/html/trust/app/Boot/Start.php(244): Foundation\Application->run()
#24 /var/www/html/trust/public/index.php(37): require('/var/www/html/t...')
#25 {main} [] []
[2016-11-03 14:05:19] production.ERROR: exception 'ReflectionException' with message 'Class App\Controllers\Admin\Settings does not exist' in /var/www/html/trust/system/Container/Container.php:507
Stack trace:
#0 /var/www/html/trust/system/Container/Container.php(507): ReflectionClass->__construct('App\\Controllers...')
#1 /var/www/html/trust/system/Container/Container.php(431): Container\Container->build('App\\Controllers...', Array)
#2 /var/www/html/trust/system/Foundation/Application.php(443): Container\Container->make('App\\Controllers...', Array)
#3 /var/www/html/trust/system/Routing/ControllerDispatcher.php(76): Foundation\Application->make('App\\Controllers...')
#4 /var/www/html/trust/system/Routing/ControllerDispatcher.php(52): Routing\ControllerDispatcher->makeController('App\\Controllers...')
#5 /var/www/html/trust/system/Routing/Router.php(958): Routing\ControllerDispatcher->dispatch(Object(Routing\Route), Object(Http\Request), 'App\\Controllers...', 'index')
#6 [internal function]: Routing\Router->Routing\{closure}()
#7 /var/www/html/trust/system/Routing/Route.php(128): call_user_func_array(Object(Closure), Array)
#8 /var/www/html/trust/system/Routing/Router.php(1026): Routing\Route->run()
#9 /var/www/html/trust/system/Routing/Router.php(994): Routing\Router->dispatchToRoute(Object(Http\Request))
#10 /var/www/html/trust/system/Foundation/Application.php(744): Routing\Router->dispatch(Object(Http\Request))
#11 /var/www/html/trust/system/Foundation/Application.php(717): Foundation\Application->dispatch(Object(Http\Request))
#12 /var/www/html/trust/shared/Http/ContentGuard.php(62): Foundation\Application->handle(Object(Http\Request), 1, true)
#13 /var/www/html/trust/system/Session/Middleware.php(77): Shared\Http\ContentGuard->handle(Object(Http\Request), 1, true)
#14 /var/www/html/trust/system/Cookie/Queue.php(49): Session\Middleware->handle(Object(Http\Request), 1, true)
#15 /var/www/html/trust/system/Cookie/Guard.php(54): Cookie\Queue->handle(Object(Http\Request), 1, true)
#16 /var/www/html/trust/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Cookie\Guard->handle(Object(Http\Request), 1, true)
#17 /var/www/html/trust/system/Foundation/Application.php(615): Stack\StackedHttpKernel->handle(Object(Http\Request))
#18 /var/www/html/trust/app/Boot/Start.php(244): Foundation\Application->run()
#19 /var/www/html/trust/public/index.php(37): require('/var/www/html/t...')
#20 {main} [] []
[2016-11-03 14:20:34] production.ERROR: exception 'ReflectionException' with message 'Class App\Controllers\Language does not exist' in /var/www/html/trust/system/Container/Container.php:507
Stack trace:
#0 /var/www/html/trust/system/Container/Container.php(507): ReflectionClass->__construct('App\\Controllers...')
#1 /var/www/html/trust/system/Container/Container.php(431): Container\Container->build('App\\Controllers...', Array)
#2 /var/www/html/trust/system/Foundation/Application.php(443): Container\Container->make('App\\Controllers...', Array)
#3 /var/www/html/trust/system/Routing/ControllerDispatcher.php(76): Foundation\Application->make('App\\Controllers...')
#4 /var/www/html/trust/system/Routing/ControllerDispatcher.php(52): Routing\ControllerDispatcher->makeController('App\\Controllers...')
#5 /var/www/html/trust/system/Routing/Router.php(958): Routing\ControllerDispatcher->dispatch(Object(Routing\Route), Object(Http\Request), 'App\\Controllers...', 'change')
#6 [internal function]: Routing\Router->Routing\{closure}('es')
#7 /var/www/html/trust/system/Routing/Route.php(128): call_user_func_array(Object(Closure), Array)
#8 /var/www/html/trust/system/Routing/Router.php(1026): Routing\Route->run()
#9 /var/www/html/trust/system/Routing/Router.php(994): Routing\Router->dispatchToRoute(Object(Http\Request))
#10 /var/www/html/trust/system/Foundation/Application.php(744): Routing\Router->dispatch(Object(Http\Request))
#11 /var/www/html/trust/system/Foundation/Application.php(717): Foundation\Application->dispatch(Object(Http\Request))
#12 /var/www/html/trust/shared/Http/ContentGuard.php(62): Foundation\Application->handle(Object(Http\Request), 1, true)
#13 /var/www/html/trust/system/Session/Middleware.php(77): Shared\Http\ContentGuard->handle(Object(Http\Request), 1, true)
#14 /var/www/html/trust/system/Cookie/Queue.php(49): Session\Middleware->handle(Object(Http\Request), 1, true)
#15 /var/www/html/trust/system/Cookie/Guard.php(54): Cookie\Queue->handle(Object(Http\Request), 1, true)
#16 /var/www/html/trust/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Cookie\Guard->handle(Object(Http\Request), 1, true)
#17 /var/www/html/trust/system/Foundation/Application.php(615): Stack\StackedHttpKernel->handle(Object(Http\Request))
#18 /var/www/html/trust/app/Boot/Start.php(244): Foundation\Application->run()
#19 /var/www/html/trust/public/index.php(37): require('/var/www/html/t...')
#20 {main} [] []
[2016-11-03 14:29:13] production.ERROR: exception 'ReflectionException' with message 'Class App\Controllers\Admin\Profile does not exist' in /var/www/html/trust/system/Container/Container.php:507
Stack trace:
#0 /var/www/html/trust/system/Container/Container.php(507): ReflectionClass->__construct('App\\Controllers...')
#1 /var/www/html/trust/system/Container/Container.php(431): Container\Container->build('App\\Controllers...', Array)
#2 /var/www/html/trust/system/Foundation/Application.php(443): Container\Container->make('App\\Controllers...', Array)
#3 /var/www/html/trust/system/Routing/ControllerDispatcher.php(76): Foundation\Application->make('App\\Controllers...')
#4 /var/www/html/trust/system/Routing/ControllerDispatcher.php(52): Routing\ControllerDispatcher->makeController('App\\Controllers...')
#5 /var/www/html/trust/system/Routing/Router.php(958): Routing\ControllerDispatcher->dispatch(Object(Routing\Route), Object(Http\Request), 'App\\Controllers...', 'index')
#6 [internal function]: Routing\Router->Routing\{closure}()
#7 /var/www/html/trust/system/Routing/Route.php(128): call_user_func_array(Object(Closure), Array)
#8 /var/www/html/trust/system/Routing/Router.php(1026): Routing\Route->run()
#9 /var/www/html/trust/system/Routing/Router.php(994): Routing\Router->dispatchToRoute(Object(Http\Request))
#10 /var/www/html/trust/system/Foundation/Application.php(744): Routing\Router->dispatch(Object(Http\Request))
#11 /var/www/html/trust/system/Foundation/Application.php(717): Foundation\Application->dispatch(Object(Http\Request))
#12 /var/www/html/trust/shared/Http/ContentGuard.php(62): Foundation\Application->handle(Object(Http\Request), 1, true)
#13 /var/www/html/trust/system/Session/Middleware.php(77): Shared\Http\ContentGuard->handle(Object(Http\Request), 1, true)
#14 /var/www/html/trust/system/Cookie/Queue.php(49): Session\Middleware->handle(Object(Http\Request), 1, true)
#15 /var/www/html/trust/system/Cookie/Guard.php(54): Cookie\Queue->handle(Object(Http\Request), 1, true)
#16 /var/www/html/trust/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Cookie\Guard->handle(Object(Http\Request), 1, true)
#17 /var/www/html/trust/system/Foundation/Application.php(615): Stack\StackedHttpKernel->handle(Object(Http\Request))
#18 /var/www/html/trust/app/Boot/Start.php(244): Foundation\Application->run()
#19 /var/www/html/trust/public/index.php(37): require('/var/www/html/t...')
#20 {main} [] []
[2016-11-03 14:38:38] production.ERROR: exception 'ReflectionException' with message 'Class App\Controllers\Admin\Profile does not exist' in /var/www/html/trust/system/Container/Container.php:507
Stack trace:
#0 /var/www/html/trust/system/Container/Container.php(507): ReflectionClass->__construct('App\\Controllers...')
#1 /var/www/html/trust/system/Container/Container.php(431): Container\Container->build('App\\Controllers...', Array)
#2 /var/www/html/trust/system/Foundation/Application.php(443): Container\Container->make('App\\Controllers...', Array)
#3 /var/www/html/trust/system/Routing/ControllerDispatcher.php(76): Foundation\Application->make('App\\Controllers...')
#4 /var/www/html/trust/system/Routing/ControllerDispatcher.php(52): Routing\ControllerDispatcher->makeController('App\\Controllers...')
#5 /var/www/html/trust/system/Routing/Router.php(958): Routing\ControllerDispatcher->dispatch(Object(Routing\Route), Object(Http\Request), 'App\\Controllers...', 'index')
#6 [internal function]: Routing\Router->Routing\{closure}()
#7 /var/www/html/trust/system/Routing/Route.php(128): call_user_func_array(Object(Closure), Array)
#8 /var/www/html/trust/system/Routing/Router.php(1026): Routing\Route->run()
#9 /var/www/html/trust/system/Routing/Router.php(994): Routing\Router->dispatchToRoute(Object(Http\Request))
#10 /var/www/html/trust/system/Foundation/Application.php(744): Routing\Router->dispatch(Object(Http\Request))
#11 /var/www/html/trust/system/Foundation/Application.php(717): Foundation\Application->dispatch(Object(Http\Request))
#12 /var/www/html/trust/shared/Http/ContentGuard.php(62): Foundation\Application->handle(Object(Http\Request), 1, true)
#13 /var/www/html/trust/system/Session/Middleware.php(77): Shared\Http\ContentGuard->handle(Object(Http\Request), 1, true)
#14 /var/www/html/trust/system/Cookie/Queue.php(49): Session\Middleware->handle(Object(Http\Request), 1, true)
#15 /var/www/html/trust/system/Cookie/Guard.php(54): Cookie\Queue->handle(Object(Http\Request), 1, true)
#16 /var/www/html/trust/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Cookie\Guard->handle(Object(Http\Request), 1, true)
#17 /var/www/html/trust/system/Foundation/Application.php(615): Stack\StackedHttpKernel->handle(Object(Http\Request))
#18 /var/www/html/trust/app/Boot/Start.php(244): Foundation\Application->run()
#19 /var/www/html/trust/public/index.php(37): require('/var/www/html/t...')
#20 {main} [] []
[2016-11-04 03:59:06] production.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected 'exit' (T_EXIT)' in C:\xampp\htdocs\trust\app\Controllers\Service.php:26
Stack trace:
#0 [internal function]: Exception\Handler->handleShutdown()
#1 {main} [] []
[2016-11-04 04:09:23] production.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected '->' (T_OBJECT_OPERATOR)' in C:\xampp\htdocs\trust\app\Controllers\Service.php:26
Stack trace:
#0 [internal function]: Exception\Handler->handleShutdown()
#1 {main} [] []
[2016-11-04 04:09:42] production.ERROR: exception 'Database\QueryException' with message 'SQLSTATE[42S02]: Base table or view not found: 1146 Table 'trust.nova_nova_forms_details' doesn't exist (SQL: select count(*) as aggregate from `nova_nova_forms_details`)' in C:\xampp\htdocs\trust\system\Database\Connection.php:548
Stack trace:
#0 C:\xampp\htdocs\trust\system\Database\Connection.php(517): Database\Connection->runQueryCallback('select count(*)...', Array, Object(Closure))
#1 C:\xampp\htdocs\trust\system\Database\Connection.php(268): Database\Connection->run('select count(*)...', Array, Object(Closure))
#2 C:\xampp\htdocs\trust\system\Database\Query\Builder.php(1334): Database\Connection->select('select count(*)...', Array)
#3 C:\xampp\htdocs\trust\system\Database\Query\Builder.php(1324): Database\Query\Builder->runSelect()
#4 C:\xampp\htdocs\trust\system\Database\Query\Builder.php(1311): Database\Query\Builder->getFresh(Array)
#5 C:\xampp\htdocs\trust\system\Database\Query\Builder.php(1719): Database\Query\Builder->get(Array)
#6 C:\xampp\htdocs\trust\system\Database\Query\Builder.php(1657): Database\Query\Builder->aggregate('count', Array)
#7 C:\xampp\htdocs\trust\app\Controllers\Service.php(21): Database\Query\Builder->count()
#8 [internal function]: App\Controllers\Service->fetch()
#9 C:\xampp\htdocs\trust\system\Routing\Controller.php(240): call_user_func_array(Array, Array)
#10 C:\xampp\htdocs\trust\system\Routing\ControllerDispatcher.php(91): Routing\Controller->callAction('fetch', Array)
#11 C:\xampp\htdocs\trust\system\Routing\ControllerDispatcher.php(60): Routing\ControllerDispatcher->call(Object(App\Controllers\Service), Object(Routing\Route), 'fetch')
#12 C:\xampp\htdocs\trust\system\Routing\Router.php(958): Routing\ControllerDispatcher->dispatch(Object(Routing\Route), Object(Http\Request), 'App\\Controllers...', 'fetch')
#13 [internal function]: Routing\Router->Routing\{closure}()
#14 C:\xampp\htdocs\trust\system\Routing\Route.php(128): call_user_func_array(Object(Closure), Array)
#15 C:\xampp\htdocs\trust\system\Routing\Router.php(1026): Routing\Route->run()
#16 C:\xampp\htdocs\trust\system\Routing\Router.php(994): Routing\Router->dispatchToRoute(Object(Http\Request))
#17 C:\xampp\htdocs\trust\system\Foundation\Application.php(744): Routing\Router->dispatch(Object(Http\Request))
#18 C:\xampp\htdocs\trust\system\Foundation\Application.php(717): Foundation\Application->dispatch(Object(Http\Request))
#19 C:\xampp\htdocs\trust\shared\Http\ContentGuard.php(62): Foundation\Application->handle(Object(Http\Request), 1, true)
#20 C:\xampp\htdocs\trust\system\Session\Middleware.php(77): Shared\Http\ContentGuard->handle(Object(Http\Request), 1, true)
#21 C:\xampp\htdocs\trust\system\Cookie\Queue.php(49): Session\Middleware->handle(Object(Http\Request), 1, true)
#22 C:\xampp\htdocs\trust\system\Cookie\Guard.php(54): Cookie\Queue->handle(Object(Http\Request), 1, true)
#23 C:\xampp\htdocs\trust\vendor\stack\builder\src\Stack\StackedHttpKernel.php(23): Cookie\Guard->handle(Object(Http\Request), 1, true)
#24 C:\xampp\htdocs\trust\system\Foundation\Application.php(615): Stack\StackedHttpKernel->handle(Object(Http\Request))
#25 C:\xampp\htdocs\trust\app\Boot\Start.php(244): Foundation\Application->run()
#26 C:\xampp\htdocs\trust\public\index.php(37): require('C:\\xampp\\htdocs...')
#27 {main} [] []
[2016-11-04 04:15:57] production.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected '0' (T_LNUMBER), expecting ',' or ';'' in C:\xampp\htdocs\trust\app\Views\Welcome\Service.php:11
Stack trace:
#0 [internal function]: Exception\Handler->handleShutdown()
#1 {main} [] []
[2016-11-04 04:16:43] production.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected '0' (T_LNUMBER), expecting ',' or ';'' in C:\xampp\htdocs\trust\app\Views\Welcome\Service.php:11
Stack trace:
#0 [internal function]: Exception\Handler->handleShutdown()
#1 {main} [] []
[2016-11-04 04:16:55] production.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected '0' (T_LNUMBER), expecting ',' or ';'' in C:\xampp\htdocs\trust\app\Views\Welcome\Service.php:9
Stack trace:
#0 [internal function]: Exception\Handler->handleShutdown()
#1 {main} [] []
[2016-11-04 04:17:12] production.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected '.'' in C:\xampp\htdocs\trust\app\Views\Welcome\Service.php:9
Stack trace:
#0 [internal function]: Exception\Handler->handleShutdown()
#1 {main} [] []
[2016-11-04 04:17:33] production.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected '.'' in C:\xampp\htdocs\trust\app\Views\Welcome\Service.php:9
Stack trace:
#0 [internal function]: Exception\Handler->handleShutdown()
#1 {main} [] []
[2016-11-04 04:17:59] production.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected '.'' in C:\xampp\htdocs\trust\app\Views\Welcome\Service.php:9
Stack trace:
#0 [internal function]: Exception\Handler->handleShutdown()
#1 {main} [] []
[2016-11-04 04:18:46] production.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected 'template_url' (T_STRING), expecting ',' or ';'' in C:\xampp\htdocs\trust\app\Views\Welcome\Service.php:9
Stack trace:
#0 [internal function]: Exception\Handler->handleShutdown()
#1 {main} [] []
[2016-11-04 04:19:12] production.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected '.'' in C:\xampp\htdocs\trust\app\Views\Welcome\Service.php:16
Stack trace:
#0 [internal function]: Exception\Handler->handleShutdown()
#1 {main} [] []
[2016-11-04 04:19:34] production.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected '.'' in C:\xampp\htdocs\trust\app\Views\Welcome\Service.php:9
Stack trace:
#0 [internal function]: Exception\Handler->handleShutdown()
#1 {main} [] []
[2016-11-04 04:21:04] production.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected '.'' in C:\xampp\htdocs\trust\app\Views\Welcome\Service.php:9
Stack trace:
#0 [internal function]: Exception\Handler->handleShutdown()
#1 {main} [] []
[2016-11-04 04:23:46] production.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected '.'' in C:\xampp\htdocs\trust\app\Views\Welcome\Service.php:9
Stack trace:
#0 [internal function]: Exception\Handler->handleShutdown()
#1 {main} [] []
[2016-11-04 04:24:05] production.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected '.'' in C:\xampp\htdocs\trust\app\Views\Welcome\Service.php:16
Stack trace:
#0 [internal function]: Exception\Handler->handleShutdown()
#1 {main} [] []
[2016-11-04 04:55:18] production.ERROR: exception 'BadMethodCallException' with message 'Method [share] does not exist on View\View' in C:\xampp\htdocs\trust\system\View\View.php:321
Stack trace:
#0 C:\xampp\htdocs\trust\app\Controllers\Service.php(36): View\View->__call('share', Array)
#1 C:\xampp\htdocs\trust\app\Controllers\Service.php(36): View\View->share('code', 'birth')
#2 [internal function]: App\Controllers\Service->fetchme('birth')
#3 C:\xampp\htdocs\trust\system\Routing\Controller.php(240): call_user_func_array(Array, Array)
#4 C:\xampp\htdocs\trust\system\Routing\ControllerDispatcher.php(91): Routing\Controller->callAction('fetchme', Array)
#5 C:\xampp\htdocs\trust\system\Routing\ControllerDispatcher.php(60): Routing\ControllerDispatcher->call(Object(App\Controllers\Service), Object(Routing\Route), 'fetchme')
#6 C:\xampp\htdocs\trust\system\Routing\Router.php(958): Routing\ControllerDispatcher->dispatch(Object(Routing\Route), Object(Http\Request), 'App\\Controllers...', 'fetchme')
#7 [internal function]: Routing\Router->Routing\{closure}('birth')
#8 C:\xampp\htdocs\trust\system\Routing\Route.php(128): call_user_func_array(Object(Closure), Array)
#9 C:\xampp\htdocs\trust\system\Routing\Router.php(1026): Routing\Route->run()
#10 C:\xampp\htdocs\trust\system\Routing\Router.php(994): Routing\Router->dispatchToRoute(Object(Http\Request))
#11 C:\xampp\htdocs\trust\system\Foundation\Application.php(744): Routing\Router->dispatch(Object(Http\Request))
#12 C:\xampp\htdocs\trust\system\Foundation\Application.php(717): Foundation\Application->dispatch(Object(Http\Request))
#13 C:\xampp\htdocs\trust\shared\Http\ContentGuard.php(62): Foundation\Application->handle(Object(Http\Request), 1, true)
#14 C:\xampp\htdocs\trust\system\Session\Middleware.php(77): Shared\Http\ContentGuard->handle(Object(Http\Request), 1, true)
#15 C:\xampp\htdocs\trust\system\Cookie\Queue.php(49): Session\Middleware->handle(Object(Http\Request), 1, true)
#16 C:\xampp\htdocs\trust\system\Cookie\Guard.php(54): Cookie\Queue->handle(Object(Http\Request), 1, true)
#17 C:\xampp\htdocs\trust\vendor\stack\builder\src\Stack\StackedHttpKernel.php(23): Cookie\Guard->handle(Object(Http\Request), 1, true)
#18 C:\xampp\htdocs\trust\system\Foundation\Application.php(615): Stack\StackedHttpKernel->handle(Object(Http\Request))
#19 C:\xampp\htdocs\trust\app\Boot\Start.php(244): Foundation\Application->run()
#20 C:\xampp\htdocs\trust\public\index.php(37): require('C:\\xampp\\htdocs...')
#21 {main} [] []
[2016-11-04 04:59:37] production.ERROR: exception 'ErrorException' with message 'Undefined variable: code' in C:\xampp\htdocs\trust\app\Views\Welcome\Form.php:2
Stack trace:
#0 C:\xampp\htdocs\trust\app\Views\Welcome\Form.php(2): Exception\Handler->handleError(8, 'Undefined varia...', 'C:\\xampp\\htdocs...', 2, Array)
#1 C:\xampp\htdocs\trust\system\View\Engines\PhpEngine.php(56): include('C:\\xampp\\htdocs...')
#2 C:\xampp\htdocs\trust\system\View\Engines\PhpEngine.php(31): View\Engines\PhpEngine->evaluatePath('C:\\xampp\\htdocs...', Array)
#3 C:\xampp\htdocs\trust\system\View\View.php(96): View\Engines\PhpEngine->get('C:\\xampp\\htdocs...', Array)
#4 C:\xampp\htdocs\trust\system\View\View.php(82): View\View->renderContents()
#5 C:\xampp\htdocs\trust\system\View\View.php(111): View\View->render()
#6 C:\xampp\htdocs\trust\system\View\View.php(96): View\View->gatherData()
#7 C:\xampp\htdocs\trust\system\View\View.php(82): View\View->renderContents()
#8 C:\xampp\htdocs\trust\app\Core\Controller.php(70): View\View->render()
#9 C:\xampp\htdocs\trust\system\Routing\Controller.php(250): App\Core\Controller->processResponse(Object(View\View))
#10 C:\xampp\htdocs\trust\system\Routing\ControllerDispatcher.php(91): Routing\Controller->callAction('fetchme', Array)
#11 C:\xampp\htdocs\trust\system\Routing\ControllerDispatcher.php(60): Routing\ControllerDispatcher->call(Object(App\Controllers\Service), Object(Routing\Route), 'fetchme')
#12 C:\xampp\htdocs\trust\system\Routing\Router.php(958): Routing\ControllerDispatcher->dispatch(Object(Routing\Route), Object(Http\Request), 'App\\Controllers...', 'fetchme')
#13 [internal function]: Routing\Router->Routing\{closure}('birth')
#14 C:\xampp\htdocs\trust\system\Routing\Route.php(128): call_user_func_array(Object(Closure), Array)
#15 C:\xampp\htdocs\trust\system\Routing\Router.php(1026): Routing\Route->run()
#16 C:\xampp\htdocs\trust\system\Routing\Router.php(994): Routing\Router->dispatchToRoute(Object(Http\Request))
#17 C:\xampp\htdocs\trust\system\Foundation\Application.php(744): Routing\Router->dispatch(Object(Http\Request))
#18 C:\xampp\htdocs\trust\system\Foundation\Application.php(717): Foundation\Application->dispatch(Object(Http\Request))
#19 C:\xampp\htdocs\trust\shared\Http\ContentGuard.php(62): Foundation\Application->handle(Object(Http\Request), 1, true)
#20 C:\xampp\htdocs\trust\system\Session\Middleware.php(77): Shared\Http\ContentGuard->handle(Object(Http\Request), 1, true)
#21 C:\xampp\htdocs\trust\system\Cookie\Queue.php(49): Session\Middleware->handle(Object(Http\Request), 1, true)
#22 C:\xampp\htdocs\trust\system\Cookie\Guard.php(54): Cookie\Queue->handle(Object(Http\Request), 1, true)
#23 C:\xampp\htdocs\trust\vendor\stack\builder\src\Stack\StackedHttpKernel.php(23): Cookie\Guard->handle(Object(Http\Request), 1, true)
#24 C:\xampp\htdocs\trust\system\Foundation\Application.php(615): Stack\StackedHttpKernel->handle(Object(Http\Request))
#25 C:\xampp\htdocs\trust\app\Boot\Start.php(244): Foundation\Application->run()
#26 C:\xampp\htdocs\trust\public\index.php(37): require('C:\\xampp\\htdocs...')
#27 {main} [] []
[2016-11-04 05:00:01] production.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected '='' in C:\xampp\htdocs\trust\app\Views\Welcome\Form.php:2
Stack trace:
#0 [internal function]: Exception\Handler->handleShutdown()
#1 {main} [] []
[2016-11-04 05:00:10] production.ERROR: exception 'ErrorException' with message 'Undefined variable: code' in C:\xampp\htdocs\trust\app\Views\Welcome\Form.php:1
Stack trace:
#0 C:\xampp\htdocs\trust\app\Views\Welcome\Form.php(1): Exception\Handler->handleError(8, 'Undefined varia...', 'C:\\xampp\\htdocs...', 1, Array)
#1 C:\xampp\htdocs\trust\system\View\Engines\PhpEngine.php(56): include('C:\\xampp\\htdocs...')
#2 C:\xampp\htdocs\trust\system\View\Engines\PhpEngine.php(31): View\Engines\PhpEngine->evaluatePath('C:\\xampp\\htdocs...', Array)
#3 C:\xampp\htdocs\trust\system\View\View.php(96): View\Engines\PhpEngine->get('C:\\xampp\\htdocs...', Array)
#4 C:\xampp\htdocs\trust\system\View\View.php(82): View\View->renderContents()
#5 C:\xampp\htdocs\trust\system\View\View.php(111): View\View->render()
#6 C:\xampp\htdocs\trust\system\View\View.php(96): View\View->gatherData()
#7 C:\xampp\htdocs\trust\system\View\View.php(82): View\View->renderContents()
#8 C:\xampp\htdocs\trust\app\Core\Controller.php(70): View\View->render()
#9 C:\xampp\htdocs\trust\system\Routing\Controller.php(250): App\Core\Controller->processResponse(Object(View\View))
#10 C:\xampp\htdocs\trust\system\Routing\ControllerDispatcher.php(91): Routing\Controller->callAction('fetchme', Array)
#11 C:\xampp\htdocs\trust\system\Routing\ControllerDispatcher.php(60): Routing\ControllerDispatcher->call(Object(App\Controllers\Service), Object(Routing\Route), 'fetchme')
#12 C:\xampp\htdocs\trust\system\Routing\Router.php(958): Routing\ControllerDispatcher->dispatch(Object(Routing\Route), Object(Http\Request), 'App\\Controllers...', 'fetchme')
#13 [internal function]: Routing\Router->Routing\{closure}('birth')
#14 C:\xampp\htdocs\trust\system\Routing\Route.php(128): call_user_func_array(Object(Closure), Array)
#15 C:\xampp\htdocs\trust\system\Routing\Router.php(1026): Routing\Route->run()
#16 C:\xampp\htdocs\trust\system\Routing\Router.php(994): Routing\Router->dispatchToRoute(Object(Http\Request))
#17 C:\xampp\htdocs\trust\system\Foundation\Application.php(744): Routing\Router->dispatch(Object(Http\Request))
#18 C:\xampp\htdocs\trust\system\Foundation\Application.php(717): Foundation\Application->dispatch(Object(Http\Request))
#19 C:\xampp\htdocs\trust\shared\Http\ContentGuard.php(62): Foundation\Application->handle(Object(Http\Request), 1, true)
#20 C:\xampp\htdocs\trust\system\Session\Middleware.php(77): Shared\Http\ContentGuard->handle(Object(Http\Request), 1, true)
#21 C:\xampp\htdocs\trust\system\Cookie\Queue.php(49): Session\Middleware->handle(Object(Http\Request), 1, true)
#22 C:\xampp\htdocs\trust\system\Cookie\Guard.php(54): Cookie\Queue->handle(Object(Http\Request), 1, true)
#23 C:\xampp\htdocs\trust\vendor\stack\builder\src\Stack\StackedHttpKernel.php(23): Cookie\Guard->handle(Object(Http\Request), 1, true)
#24 C:\xampp\htdocs\trust\system\Foundation\Application.php(615): Stack\StackedHttpKernel->handle(Object(Http\Request))
#25 C:\xampp\htdocs\trust\app\Boot\Start.php(244): Foundation\Application->run()
#26 C:\xampp\htdocs\trust\public\index.php(37): require('C:\\xampp\\htdocs...')
#27 {main} [] []
[2016-11-04 06:36:25] production.ERROR: exception 'ErrorException' with message 'call_user_func_array() expects parameter 1 to be a valid callback, no array or string given' in C:\xampp\htdocs\trust\system\Routing\Route.php:128
Stack trace:
#0 [internal function]: Exception\Handler->handleError(2, 'call_user_func_...', 'C:\\xampp\\htdocs...', 128, Array)
#1 C:\xampp\htdocs\trust\system\Routing\Route.php(128): call_user_func_array(NULL, Array)
#2 C:\xampp\htdocs\trust\system\Routing\Router.php(1026): Routing\Route->run()
#3 C:\xampp\htdocs\trust\system\Routing\Router.php(994): Routing\Router->dispatchToRoute(Object(Http\Request))
#4 C:\xampp\htdocs\trust\system\Foundation\Application.php(744): Routing\Router->dispatch(Object(Http\Request))
#5 C:\xampp\htdocs\trust\system\Foundation\Application.php(717): Foundation\Application->dispatch(Object(Http\Request))
#6 C:\xampp\htdocs\trust\shared\Http\ContentGuard.php(62): Foundation\Application->handle(Object(Http\Request), 1, true)
#7 C:\xampp\htdocs\trust\system\Session\Middleware.php(77): Shared\Http\ContentGuard->handle(Object(Http\Request), 1, true)
#8 C:\xampp\htdocs\trust\system\Cookie\Queue.php(49): Session\Middleware->handle(Object(Http\Request), 1, true)
#9 C:\xampp\htdocs\trust\system\Cookie\Guard.php(54): Cookie\Queue->handle(Object(Http\Request), 1, true)
#10 C:\xampp\htdocs\trust\vendor\stack\builder\src\Stack\StackedHttpKernel.php(23): Cookie\Guard->handle(Object(Http\Request), 1, true)
#11 C:\xampp\htdocs\trust\system\Foundation\Application.php(615): Stack\StackedHttpKernel->handle(Object(Http\Request))
#12 C:\xampp\htdocs\trust\app\Boot\Start.php(244): Foundation\Application->run()
#13 C:\xampp\htdocs\trust\public\index.php(37): require('C:\\xampp\\htdocs...')
#14 {main} [] []
[2016-11-04 06:37:02] production.ERROR: exception 'BadMethodCallException' with message 'Method [fetch] does not exist.' in C:\xampp\htdocs\trust\system\Routing\Controller.php:293
Stack trace:
#0 [internal function]: Routing\Controller->__call('fetch', Array)
#1 [internal function]: App\Controllers\Welcome->fetch()
#2 C:\xampp\htdocs\trust\system\Routing\Controller.php(240): call_user_func_array(Array, Array)
#3 C:\xampp\htdocs\trust\system\Routing\ControllerDispatcher.php(91): Routing\Controller->callAction('fetch', Array)
#4 C:\xampp\htdocs\trust\system\Routing\ControllerDispatcher.php(60): Routing\ControllerDispatcher->call(Object(App\Controllers\Welcome), Object(Routing\Route), 'fetch')
#5 C:\xampp\htdocs\trust\system\Routing\Router.php(958): Routing\ControllerDispatcher->dispatch(Object(Routing\Route), Object(Http\Request), 'App\\Controllers...', 'fetch')
#6 [internal function]: Routing\Router->Routing\{closure}()
#7 C:\xampp\htdocs\trust\system\Routing\Route.php(128): call_user_func_array(Object(Closure), Array)
#8 C:\xampp\htdocs\trust\system\Routing\Router.php(1026): Routing\Route->run()
#9 C:\xampp\htdocs\trust\system\Routing\Router.php(994): Routing\Router->dispatchToRoute(Object(Http\Request))
#10 C:\xampp\htdocs\trust\system\Foundation\Application.php(744): Routing\Router->dispatch(Object(Http\Request))
#11 C:\xampp\htdocs\trust\system\Foundation\Application.php(717): Foundation\Application->dispatch(Object(Http\Request))
#12 C:\xampp\htdocs\trust\shared\Http\ContentGuard.php(62): Foundation\Application->handle(Object(Http\Request), 1, true)
#13 C:\xampp\htdocs\trust\system\Session\Middleware.php(77): Shared\Http\ContentGuard->handle(Object(Http\Request), 1, true)
#14 C:\xampp\htdocs\trust\system\Cookie\Queue.php(49): Session\Middleware->handle(Object(Http\Request), 1, true)
#15 C:\xampp\htdocs\trust\system\Cookie\Guard.php(54): Cookie\Queue->handle(Object(Http\Request), 1, true)
#16 C:\xampp\htdocs\trust\vendor\stack\builder\src\Stack\StackedHttpKernel.php(23): Cookie\Guard->handle(Object(Http\Request), 1, true)
#17 C:\xampp\htdocs\trust\system\Foundation\Application.php(615): Stack\StackedHttpKernel->handle(Object(Http\Request))
#18 C:\xampp\htdocs\trust\app\Boot\Start.php(244): Foundation\Application->run()
#19 C:\xampp\htdocs\trust\public\index.php(37): require('C:\\xampp\\htdocs...')
#20 {main} [] []
[2016-11-04 09:18:09] production.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected '}'' in C:\xampp\htdocs\trust\app\Controllers\Admin\Family.php:37
Stack trace:
#0 [internal function]: Exception\Handler->handleShutdown()
#1 {main} [] []
[2016-11-04 10:11:43] production.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected end of file' in C:\xampp\htdocs\trust\app\Templates\AdminLte\backend.php:244
Stack trace:
#0 [internal function]: Exception\Handler->handleShutdown()
#1 {main} [] []
[2016-11-04 10:14:35] production.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Class 'App\Modules\Files\Controllers\Admin\Redirect' not found' in C:\xampp\htdocs\trust\app\Modules\Files\Controllers\Admin\Files.php:74
Stack trace:
#0 [internal function]: Exception\Handler->handleShutdown()
#1 {main} [] []
[2016-11-04 10:15:01] production.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected '}'' in C:\xampp\htdocs\trust\app\Templates\AdminLte\backend.php:188
Stack trace:
#0 [internal function]: Exception\Handler->handleShutdown()
#1 {main} [] []
[2016-11-04 10:15:04] production.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected '}'' in C:\xampp\htdocs\trust\app\Templates\AdminLte\backend.php:188
Stack trace:
#0 [internal function]: Exception\Handler->handleShutdown()
#1 {main} [] []
[2016-11-04 10:23:33] production.ERROR: exception 'InvalidArgumentException' with message 'Filter method [@UsersFilter] does not exist.' in C:\xampp\htdocs\trust\system\Routing\Controller.php:137
Stack trace:
#0 C:\xampp\htdocs\trust\system\Routing\Controller.php(85): Routing\Controller->isInstanceFilter('@UsersFilter')
#1 C:\xampp\htdocs\trust\system\Routing\Controller.php(55): Routing\Controller->parseFilter('@UsersFilter', Array)
#2 C:\xampp\htdocs\trust\app\Controllers\Admin\Family.php(28): Routing\Controller->beforeFilter('@UsersFilter')
#3 [internal function]: App\Controllers\Admin\Family->__construct()
#4 C:\xampp\htdocs\trust\system\Container\Container.php(542): ReflectionClass->newInstanceArgs(Array)
#5 C:\xampp\htdocs\trust\system\Container\Container.php(431): Container\Container->build('App\\Controllers...', Array)
#6 C:\xampp\htdocs\trust\system\Foundation\Application.php(443): Container\Container->make('App\\Controllers...', Array)
#7 C:\xampp\htdocs\trust\system\Routing\ControllerDispatcher.php(76): Foundation\Application->make('App\\Controllers...')
#8 C:\xampp\htdocs\trust\system\Routing\ControllerDispatcher.php(52): Routing\ControllerDispatcher->makeController('App\\Controllers...')
#9 C:\xampp\htdocs\trust\system\Routing\Router.php(958): Routing\ControllerDispatcher->dispatch(Object(Routing\Route), Object(Http\Request), 'App\\Controllers...', 'index')
#10 [internal function]: Routing\Router->Routing\{closure}()
#11 C:\xampp\htdocs\trust\system\Routing\Route.php(128): call_user_func_array(Object(Closure), Array)
#12 C:\xampp\htdocs\trust\system\Routing\Router.php(1026): Routing\Route->run()
#13 C:\xampp\htdocs\trust\system\Routing\Router.php(994): Routing\Router->dispatchToRoute(Object(Http\Request))
#14 C:\xampp\htdocs\trust\system\Foundation\Application.php(744): Routing\Router->dispatch(Object(Http\Request))
#15 C:\xampp\htdocs\trust\system\Foundation\Application.php(717): Foundation\Application->dispatch(Object(Http\Request))
#16 C:\xampp\htdocs\trust\shared\Http\ContentGuard.php(62): Foundation\Application->handle(Object(Http\Request), 1, true)
#17 C:\xampp\htdocs\trust\system\Session\Middleware.php(77): Shared\Http\ContentGuard->handle(Object(Http\Request), 1, true)
#18 C:\xampp\htdocs\trust\system\Cookie\Queue.php(49): Session\Middleware->handle(Object(Http\Request), 1, true)
#19 C:\xampp\htdocs\trust\system\Cookie\Guard.php(54): Cookie\Queue->handle(Object(Http\Request), 1, true)
#20 C:\xampp\htdocs\trust\vendor\stack\builder\src\Stack\StackedHttpKernel.php(23): Cookie\Guard->handle(Object(Http\Request), 1, true)
#21 C:\xampp\htdocs\trust\system\Foundation\Application.php(615): Stack\StackedHttpKernel->handle(Object(Http\Request))
#22 C:\xampp\htdocs\trust\app\Boot\Start.php(244): Foundation\Application->run()
#23 C:\xampp\htdocs\trust\public\index.php(37): require('C:\\xampp\\htdocs...')
#24 {main} [] []
[2016-11-04 10:24:39] production.ERROR: exception 'InvalidArgumentException' with message 'Filter method [@userUsersFilter] does not exist.' in C:\xampp\htdocs\trust\system\Routing\Controller.php:137
Stack trace:
#0 C:\xampp\htdocs\trust\system\Routing\Controller.php(85): Routing\Controller->isInstanceFilter('@userUsersFilte...')
#1 C:\xampp\htdocs\trust\system\Routing\Controller.php(55): Routing\Controller->parseFilter('@userUsersFilte...', Array)
#2 C:\xampp\htdocs\trust\app\Controllers\Admin\Family.php(28): Routing\Controller->beforeFilter('@userUsersFilte...')
#3 [internal function]: App\Controllers\Admin\Family->__construct()
#4 C:\xampp\htdocs\trust\system\Container\Container.php(542): ReflectionClass->newInstanceArgs(Array)
#5 C:\xampp\htdocs\trust\system\Container\Container.php(431): Container\Container->build('App\\Controllers...', Array)
#6 C:\xampp\htdocs\trust\system\Foundation\Application.php(443): Container\Container->make('App\\Controllers...', Array)
#7 C:\xampp\htdocs\trust\system\Routing\ControllerDispatcher.php(76): Foundation\Application->make('App\\Controllers...')
#8 C:\xampp\htdocs\trust\system\Routing\ControllerDispatcher.php(52): Routing\ControllerDispatcher->makeController('App\\Controllers...')
#9 C:\xampp\htdocs\trust\system\Routing\Router.php(958): Routing\ControllerDispatcher->dispatch(Object(Routing\Route), Object(Http\Request), 'App\\Controllers...', 'index')
#10 [internal function]: Routing\Router->Routing\{closure}()
#11 C:\xampp\htdocs\trust\system\Routing\Route.php(128): call_user_func_array(Object(Closure), Array)
#12 C:\xampp\htdocs\trust\system\Routing\Router.php(1026): Routing\Route->run()
#13 C:\xampp\htdocs\trust\system\Routing\Router.php(994): Routing\Router->dispatchToRoute(Object(Http\Request))
#14 C:\xampp\htdocs\trust\system\Foundation\Application.php(744): Routing\Router->dispatch(Object(Http\Request))
#15 C:\xampp\htdocs\trust\system\Foundation\Application.php(717): Foundation\Application->dispatch(Object(Http\Request))
#16 C:\xampp\htdocs\trust\shared\Http\ContentGuard.php(62): Foundation\Application->handle(Object(Http\Request), 1, true)
#17 C:\xampp\htdocs\trust\system\Session\Middleware.php(77): Shared\Http\ContentGuard->handle(Object(Http\Request), 1, true)
#18 C:\xampp\htdocs\trust\system\Cookie\Queue.php(49): Session\Middleware->handle(Object(Http\Request), 1, true)
#19 C:\xampp\htdocs\trust\system\Cookie\Guard.php(54): Cookie\Queue->handle(Object(Http\Request), 1, true)
#20 C:\xampp\htdocs\trust\vendor\stack\builder\src\Stack\StackedHttpKernel.php(23): Cookie\Guard->handle(Object(Http\Request), 1, true)
#21 C:\xampp\htdocs\trust\system\Foundation\Application.php(615): Stack\StackedHttpKernel->handle(Object(Http\Request))
#22 C:\xampp\htdocs\trust\app\Boot\Start.php(244): Foundation\Application->run()
#23 C:\xampp\htdocs\trust\public\index.php(37): require('C:\\xampp\\htdocs...')
#24 {main} [] []
[2016-11-04 10:24:50] production.ERROR: exception 'InvalidArgumentException' with message 'Filter method [@UsersFilter] does not exist.' in C:\xampp\htdocs\trust\system\Routing\Controller.php:137
Stack trace:
#0 C:\xampp\htdocs\trust\system\Routing\Controller.php(85): Routing\Controller->isInstanceFilter('@UsersFilter')
#1 C:\xampp\htdocs\trust\system\Routing\Controller.php(55): Routing\Controller->parseFilter('@UsersFilter', Array)
#2 C:\xampp\htdocs\trust\app\Controllers\Admin\Family.php(28): Routing\Controller->beforeFilter('@UsersFilter')
#3 [internal function]: App\Controllers\Admin\Family->__construct()
#4 C:\xampp\htdocs\trust\system\Container\Container.php(542): ReflectionClass->newInstanceArgs(Array)
#5 C:\xampp\htdocs\trust\system\Container\Container.php(431): Container\Container->build('App\\Controllers...', Array)
#6 C:\xampp\htdocs\trust\system\Foundation\Application.php(443): Container\Container->make('App\\Controllers...', Array)
#7 C:\xampp\htdocs\trust\system\Routing\ControllerDispatcher.php(76): Foundation\Application->make('App\\Controllers...')
#8 C:\xampp\htdocs\trust\system\Routing\ControllerDispatcher.php(52): Routing\ControllerDispatcher->makeController('App\\Controllers...')
#9 C:\xampp\htdocs\trust\system\Routing\Router.php(958): Routing\ControllerDispatcher->dispatch(Object(Routing\Route), Object(Http\Request), 'App\\Controllers...', 'index')
#10 [internal function]: Routing\Router->Routing\{closure}()
#11 C:\xampp\htdocs\trust\system\Routing\Route.php(128): call_user_func_array(Object(Closure), Array)
#12 C:\xampp\htdocs\trust\system\Routing\Router.php(1026): Routing\Route->run()
#13 C:\xampp\htdocs\trust\system\Routing\Router.php(994): Routing\Router->dispatchToRoute(Object(Http\Request))
#14 C:\xampp\htdocs\trust\system\Foundation\Application.php(744): Routing\Router->dispatch(Object(Http\Request))
#15 C:\xampp\htdocs\trust\system\Foundation\Application.php(717): Foundation\Application->dispatch(Object(Http\Request))
#16 C:\xampp\htdocs\trust\shared\Http\ContentGuard.php(62): Foundation\Application->handle(Object(Http\Request), 1, true)
#17 C:\xampp\htdocs\trust\system\Session\Middleware.php(77): Shared\Http\ContentGuard->handle(Object(Http\Request), 1, true)
#18 C:\xampp\htdocs\trust\system\Cookie\Queue.php(49): Session\Middleware->handle(Object(Http\Request), 1, true)
#19 C:\xampp\htdocs\trust\system\Cookie\Guard.php(54): Cookie\Queue->handle(Object(Http\Request), 1, true)
#20 C:\xampp\htdocs\trust\vendor\stack\builder\src\Stack\StackedHttpKernel.php(23): Cookie\Guard->handle(Object(Http\Request), 1, true)
#21 C:\xampp\htdocs\trust\system\Foundation\Application.php(615): Stack\StackedHttpKernel->handle(Object(Http\Request))
#22 C:\xampp\htdocs\trust\app\Boot\Start.php(244): Foundation\Application->run()
#23 C:\xampp\htdocs\trust\public\index.php(37): require('C:\\xampp\\htdocs...')
#24 {main} [] []
[2016-11-04 10:25:22] production.ERROR: exception 'InvalidArgumentException' with message 'Filter method [@user] does not exist.' in C:\xampp\htdocs\trust\system\Routing\Controller.php:137
Stack trace:
#0 C:\xampp\htdocs\trust\system\Routing\Controller.php(85): Routing\Controller->isInstanceFilter('@user')
#1 C:\xampp\htdocs\trust\system\Routing\Controller.php(55): Routing\Controller->parseFilter('@user', Array)
#2 C:\xampp\htdocs\trust\app\Controllers\Admin\Family.php(28): Routing\Controller->beforeFilter('@user')
#3 [internal function]: App\Controllers\Admin\Family->__construct()
#4 C:\xampp\htdocs\trust\system\Container\Container.php(542): ReflectionClass->newInstanceArgs(Array)
#5 C:\xampp\htdocs\trust\system\Container\Container.php(431): Container\Container->build('App\\Controllers...', Array)
#6 C:\xampp\htdocs\trust\system\Foundation\Application.php(443): Container\Container->make('App\\Controllers...', Array)
#7 C:\xampp\htdocs\trust\system\Routing\ControllerDispatcher.php(76): Foundation\Application->make('App\\Controllers...')
#8 C:\xampp\htdocs\trust\system\Routing\ControllerDispatcher.php(52): Routing\ControllerDispatcher->makeController('App\\Controllers...')
#9 C:\xampp\htdocs\trust\system\Routing\Router.php(958): Routing\ControllerDispatcher->dispatch(Object(Routing\Route), Object(Http\Request), 'App\\Controllers...', 'index')
#10 [internal function]: Routing\Router->Routing\{closure}()
#11 C:\xampp\htdocs\trust\system\Routing\Route.php(128): call_user_func_array(Object(Closure), Array)
#12 C:\xampp\htdocs\trust\system\Routing\Router.php(1026): Routing\Route->run()
#13 C:\xampp\htdocs\trust\system\Routing\Router.php(994): Routing\Router->dispatchToRoute(Object(Http\Request))
#14 C:\xampp\htdocs\trust\system\Foundation\Application.php(744): Routing\Router->dispatch(Object(Http\Request))
#15 C:\xampp\htdocs\trust\system\Foundation\Application.php(717): Foundation\Application->dispatch(Object(Http\Request))
#16 C:\xampp\htdocs\trust\shared\Http\ContentGuard.php(62): Foundation\Application->handle(Object(Http\Request), 1, true)
#17 C:\xampp\htdocs\trust\system\Session\Middleware.php(77): Shared\Http\ContentGuard->handle(Object(Http\Request), 1, true)
#18 C:\xampp\htdocs\trust\system\Cookie\Queue.php(49): Session\Middleware->handle(Object(Http\Request), 1, true)
#19 C:\xampp\htdocs\trust\system\Cookie\Guard.php(54): Cookie\Queue->handle(Object(Http\Request), 1, true)
#20 C:\xampp\htdocs\trust\vendor\stack\builder\src\Stack\StackedHttpKernel.php(23): Cookie\Guard->handle(Object(Http\Request), 1, true)
#21 C:\xampp\htdocs\trust\system\Foundation\Application.php(615): Stack\StackedHttpKernel->handle(Object(Http\Request))
#22 C:\xampp\htdocs\trust\app\Boot\Start.php(244): Foundation\Application->run()
#23 C:\xampp\htdocs\trust\public\index.php(37): require('C:\\xampp\\htdocs...')
#24 {main} [] []
[2016-11-04 10:39:36] production.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected 'return' (T_RETURN)' in C:\xampp\htdocs\trust\app\Controllers\Admin\Family.php:30
Stack trace:
#0 [internal function]: Exception\Handler->handleShutdown()
#1 {main} [] []
[2016-11-04 10:45:55] production.ERROR: exception 'Database\QueryException' with message 'SQLSTATE[42S02]: Base table or view not found: 1146 Table 'trust.nova_user' doesn't exist (SQL: select * from `nova_family_relation_joins` inner join `nova_user` on `nova_family_tree_groups`.`treeID` = `nova_user`.`family_id` where `nova_family_relation_joins`.`userID` = 2)' in C:\xampp\htdocs\trust\system\Database\Connection.php:548
Stack trace:
#0 C:\xampp\htdocs\trust\system\Database\Connection.php(517): Database\Connection->runQueryCallback('select * from `...', Array, Object(Closure))
#1 C:\xampp\htdocs\trust\system\Database\Connection.php(268): Database\Connection->run('select * from `...', Array, Object(Closure))
#2 C:\xampp\htdocs\trust\system\Database\Query\Builder.php(1334): Database\Connection->select('select * from `...', Array)
#3 C:\xampp\htdocs\trust\system\Database\Query\Builder.php(1324): Database\Query\Builder->runSelect()
#4 C:\xampp\htdocs\trust\system\Database\Query\Builder.php(1311): Database\Query\Builder->getFresh(Array)
#5 C:\xampp\htdocs\trust\app\Controllers\Admin\Family.php(31): Database\Query\Builder->get()
#6 [internal function]: App\Controllers\Admin\Family->index()
#7 C:\xampp\htdocs\trust\system\Routing\Controller.php(240): call_user_func_array(Array, Array)
#8 C:\xampp\htdocs\trust\system\Routing\ControllerDispatcher.php(91): Routing\Controller->callAction('index', Array)
#9 C:\xampp\htdocs\trust\system\Routing\ControllerDispatcher.php(60): Routing\ControllerDispatcher->call(Object(App\Controllers\Admin\Family), Object(Routing\Route), 'index')
#10 C:\xampp\htdocs\trust\system\Routing\Router.php(958): Routing\ControllerDispatcher->dispatch(Object(Routing\Route), Object(Http\Request), 'App\\Controllers...', 'index')
#11 [internal function]: Routing\Router->Routing\{closure}()
#12 C:\xampp\htdocs\trust\system\Routing\Route.php(128): call_user_func_array(Object(Closure), Array)
#13 C:\xampp\htdocs\trust\system\Routing\Router.php(1026): Routing\Route->run()
#14 C:\xampp\htdocs\trust\system\Routing\Router.php(994): Routing\Router->dispatchToRoute(Object(Http\Request))
#15 C:\xampp\htdocs\trust\system\Foundation\Application.php(744): Routing\Router->dispatch(Object(Http\Request))
#16 C:\xampp\htdocs\trust\system\Foundation\Application.php(717): Foundation\Application->dispatch(Object(Http\Request))
#17 C:\xampp\htdocs\trust\shared\Http\ContentGuard.php(62): Foundation\Application->handle(Object(Http\Request), 1, true)
#18 C:\xampp\htdocs\trust\system\Session\Middleware.php(77): Shared\Http\ContentGuard->handle(Object(Http\Request), 1, true)
#19 C:\xampp\htdocs\trust\system\Cookie\Queue.php(49): Session\Middleware->handle(Object(Http\Request), 1, true)
#20 C:\xampp\htdocs\trust\system\Cookie\Guard.php(54): Cookie\Queue->handle(Object(Http\Request), 1, true)
#21 C:\xampp\htdocs\trust\vendor\stack\builder\src\Stack\StackedHttpKernel.php(23): Cookie\Guard->handle(Object(Http\Request), 1, true)
#22 C:\xampp\htdocs\trust\system\Foundation\Application.php(615): Stack\StackedHttpKernel->handle(Object(Http\Request))
#23 C:\xampp\htdocs\trust\app\Boot\Start.php(244): Foundation\Application->run()
#24 C:\xampp\htdocs\trust\public\index.php(37): require('C:\\xampp\\htdocs...')
#25 {main} [] []
[2016-11-04 10:46:22] production.ERROR: exception 'Database\QueryException' with message 'SQLSTATE[42S22]: Column not found: 1054 Unknown column 'nova_family_tree_groups.treeID' in 'on clause' (SQL: select * from `nova_family_relation_joins` inner join `nova_users` on `nova_family_tree_groups`.`treeID` = `nova_user`.`family_id` where `nova_family_relation_joins`.`userID` = 2)' in C:\xampp\htdocs\trust\system\Database\Connection.php:548
Stack trace:
#0 C:\xampp\htdocs\trust\system\Database\Connection.php(517): Database\Connection->runQueryCallback('select * from `...', Array, Object(Closure))
#1 C:\xampp\htdocs\trust\system\Database\Connection.php(268): Database\Connection->run('select * from `...', Array, Object(Closure))
#2 C:\xampp\htdocs\trust\system\Database\Query\Builder.php(1334): Database\Connection->select('select * from `...', Array)
#3 C:\xampp\htdocs\trust\system\Database\Query\Builder.php(1324): Database\Query\Builder->runSelect()
#4 C:\xampp\htdocs\trust\system\Database\Query\Builder.php(1311): Database\Query\Builder->getFresh(Array)
#5 C:\xampp\htdocs\trust\app\Controllers\Admin\Family.php(31): Database\Query\Builder->get()
#6 [internal function]: App\Controllers\Admin\Family->index()
#7 C:\xampp\htdocs\trust\system\Routing\Controller.php(240): call_user_func_array(Array, Array)
#8 C:\xampp\htdocs\trust\system\Routing\ControllerDispatcher.php(91): Routing\Controller->callAction('index', Array)
#9 C:\xampp\htdocs\trust\system\Routing\ControllerDispatcher.php(60): Routing\ControllerDispatcher->call(Object(App\Controllers\Admin\Family), Object(Routing\Route), 'index')
#10 C:\xampp\htdocs\trust\system\Routing\Router.php(958): Routing\ControllerDispatcher->dispatch(Object(Routing\Route), Object(Http\Request), 'App\\Controllers...', 'index')
#11 [internal function]: Routing\Router->Routing\{closure}()
#12 C:\xampp\htdocs\trust\system\Routing\Route.php(128): call_user_func_array(Object(Closure), Array)
#13 C:\xampp\htdocs\trust\system\Routing\Router.php(1026): Routing\Route->run()
#14 C:\xampp\htdocs\trust\system\Routing\Router.php(994): Routing\Router->dispatchToRoute(Object(Http\Request))
#15 C:\xampp\htdocs\trust\system\Foundation\Application.php(744): Routing\Router->dispatch(Object(Http\Request))
#16 C:\xampp\htdocs\trust\system\Foundation\Application.php(717): Foundation\Application->dispatch(Object(Http\Request))
#17 C:\xampp\htdocs\trust\shared\Http\ContentGuard.php(62): Foundation\Application->handle(Object(Http\Request), 1, true)
#18 C:\xampp\htdocs\trust\system\Session\Middleware.php(77): Shared\Http\ContentGuard->handle(Object(Http\Request), 1, true)
#19 C:\xampp\htdocs\trust\system\Cookie\Queue.php(49): Session\Middleware->handle(Object(Http\Request), 1, true)
#20 C:\xampp\htdocs\trust\system\Cookie\Guard.php(54): Cookie\Queue->handle(Object(Http\Request), 1, true)
#21 C:\xampp\htdocs\trust\vendor\stack\builder\src\Stack\StackedHttpKernel.php(23): Cookie\Guard->handle(Object(Http\Request), 1, true)
#22 C:\xampp\htdocs\trust\system\Foundation\Application.php(615): Stack\StackedHttpKernel->handle(Object(Http\Request))
#23 C:\xampp\htdocs\trust\app\Boot\Start.php(244): Foundation\Application->run()
#24 C:\xampp\htdocs\trust\public\index.php(37): require('C:\\xampp\\htdocs...')
#25 {main} [] []
[2016-11-04 10:48:02] production.ERROR: exception 'Database\QueryException' with message 'SQLSTATE[42S22]: Column not found: 1054 Unknown column 'nova_family_tree_groups.treeID' in 'on clause' (SQL: select * from `nova_family_relation_joins` inner join `nova_users` on `nova_family_tree_groups`.`treeID` = `nova_user`.`family_id` where `nova_family_relation_joins`.`userID` = 2)' in C:\xampp\htdocs\trust\system\Database\Connection.php:548
Stack trace:
#0 C:\xampp\htdocs\trust\system\Database\Connection.php(517): Database\Connection->runQueryCallback('select * from `...', Array, Object(Closure))
#1 C:\xampp\htdocs\trust\system\Database\Connection.php(268): Database\Connection->run('select * from `...', Array, Object(Closure))
#2 C:\xampp\htdocs\trust\system\Database\Query\Builder.php(1334): Database\Connection->select('select * from `...', Array)
#3 C:\xampp\htdocs\trust\system\Database\Query\Builder.php(1324): Database\Query\Builder->runSelect()
#4 C:\xampp\htdocs\trust\system\Database\Query\Builder.php(1311): Database\Query\Builder->getFresh(Array)
#5 C:\xampp\htdocs\trust\app\Controllers\Admin\Family.php(31): Database\Query\Builder->get()
#6 [internal function]: App\Controllers\Admin\Family->index()
#7 C:\xampp\htdocs\trust\system\Routing\Controller.php(240): call_user_func_array(Array, Array)
#8 C:\xampp\htdocs\trust\system\Routing\ControllerDispatcher.php(91): Routing\Controller->callAction('index', Array)
#9 C:\xampp\htdocs\trust\system\Routing\ControllerDispatcher.php(60): Routing\ControllerDispatcher->call(Object(App\Controllers\Admin\Family), Object(Routing\Route), 'index')
#10 C:\xampp\htdocs\trust\system\Routing\Router.php(958): Routing\ControllerDispatcher->dispatch(Object(Routing\Route), Object(Http\Request), 'App\\Controllers...', 'index')
#11 [internal function]: Routing\Router->Routing\{closure}()
#12 C:\xampp\htdocs\trust\system\Routing\Route.php(128): call_user_func_array(Object(Closure), Array)
#13 C:\xampp\htdocs\trust\system\Routing\Router.php(1026): Routing\Route->run()
#14 C:\xampp\htdocs\trust\system\Routing\Router.php(994): Routing\Router->dispatchToRoute(Object(Http\Request))
#15 C:\xampp\htdocs\trust\system\Foundation\Application.php(744): Routing\Router->dispatch(Object(Http\Request))
#16 C:\xampp\htdocs\trust\system\Foundation\Application.php(717): Foundation\Application->dispatch(Object(Http\Request))
#17 C:\xampp\htdocs\trust\shared\Http\ContentGuard.php(62): Foundation\Application->handle(Object(Http\Request), 1, true)
#18 C:\xampp\htdocs\trust\system\Session\Middleware.php(77): Shared\Http\ContentGuard->handle(Object(Http\Request), 1, true)
#19 C:\xampp\htdocs\trust\system\Cookie\Queue.php(49): Session\Middleware->handle(Object(Http\Request), 1, true)
#20 C:\xampp\htdocs\trust\system\Cookie\Guard.php(54): Cookie\Queue->handle(Object(Http\Request), 1, true)
#21 C:\xampp\htdocs\trust\vendor\stack\builder\src\Stack\StackedHttpKernel.php(23): Cookie\Guard->handle(Object(Http\Request), 1, true)
#22 C:\xampp\htdocs\trust\system\Foundation\Application.php(615): Stack\StackedHttpKernel->handle(Object(Http\Request))
#23 C:\xampp\htdocs\trust\app\Boot\Start.php(244): Foundation\Application->run()
#24 C:\xampp\htdocs\trust\public\index.php(37): require('C:\\xampp\\htdocs...')
#25 {main} [] []
[2016-11-04 10:51:27] production.ERROR: exception 'Database\QueryException' with message 'SQLSTATE[42S22]: Column not found: 1054 Unknown column 'nova_family_tree_groups.treeID' in 'on clause' (SQL: select * from `nova_family_relation_joins` inner join `nova_users` on `nova_family_tree_groups`.`treeID` = `nova_user`.`family_id` where `nova_family_relation_joins`.`userID` = 2)' in C:\xampp\htdocs\trust\system\Database\Connection.php:548
Stack trace:
#0 C:\xampp\htdocs\trust\system\Database\Connection.php(517): Database\Connection->runQueryCallback('select * from `...', Array, Object(Closure))
#1 C:\xampp\htdocs\trust\system\Database\Connection.php(268): Database\Connection->run('select * from `...', Array, Object(Closure))
#2 C:\xampp\htdocs\trust\system\Database\Query\Builder.php(1334): Database\Connection->select('select * from `...', Array)
#3 C:\xampp\htdocs\trust\system\Database\Query\Builder.php(1324): Database\Query\Builder->runSelect()
#4 C:\xampp\htdocs\trust\system\Database\Query\Builder.php(1311): Database\Query\Builder->getFresh(Array)
#5 C:\xampp\htdocs\trust\app\Controllers\Admin\Family.php(31): Database\Query\Builder->get()
#6 [internal function]: App\Controllers\Admin\Family->index()
#7 C:\xampp\htdocs\trust\system\Routing\Controller.php(240): call_user_func_array(Array, Array)
#8 C:\xampp\htdocs\trust\system\Routing\ControllerDispatcher.php(91): Routing\Controller->callAction('index', Array)
#9 C:\xampp\htdocs\trust\system\Routing\ControllerDispatcher.php(60): Routing\ControllerDispatcher->call(Object(App\Controllers\Admin\Family), Object(Routing\Route), 'index')
#10 C:\xampp\htdocs\trust\system\Routing\Router.php(958): Routing\ControllerDispatcher->dispatch(Object(Routing\Route), Object(Http\Request), 'App\\Controllers...', 'index')
#11 [internal function]: Routing\Router->Routing\{closure}()
#12 C:\xampp\htdocs\trust\system\Routing\Route.php(128): call_user_func_array(Object(Closure), Array)
#13 C:\xampp\htdocs\trust\system\Routing\Router.php(1026): Routing\Route->run()
#14 C:\xampp\htdocs\trust\system\Routing\Router.php(994): Routing\Router->dispatchToRoute(Object(Http\Request))
#15 C:\xampp\htdocs\trust\system\Foundation\Application.php(744): Routing\Router->dispatch(Object(Http\Request))
#16 C:\xampp\htdocs\trust\system\Foundation\Application.php(717): Foundation\Application->dispatch(Object(Http\Request))
#17 C:\xampp\htdocs\trust\shared\Http\ContentGuard.php(62): Foundation\Application->handle(Object(Http\Request), 1, true)
#18 C:\xampp\htdocs\trust\system\Session\Middleware.php(77): Shared\Http\ContentGuard->handle(Object(Http\Request), 1, true)
#19 C:\xampp\htdocs\trust\system\Cookie\Queue.php(49): Session\Middleware->handle(Object(Http\Request), 1, true)
#20 C:\xampp\htdocs\trust\system\Cookie\Guard.php(54): Cookie\Queue->handle(Object(Http\Request), 1, true)
#21 C:\xampp\htdocs\trust\vendor\stack\builder\src\Stack\StackedHttpKernel.php(23): Cookie\Guard->handle(Object(Http\Request), 1, true)
#22 C:\xampp\htdocs\trust\system\Foundation\Application.php(615): Stack\StackedHttpKernel->handle(Object(Http\Request))
#23 C:\xampp\htdocs\trust\app\Boot\Start.php(244): Foundation\Application->run()
#24 C:\xampp\htdocs\trust\public\index.php(37): require('C:\\xampp\\htdocs...')
#25 {main} [] []
[2016-11-04 10:54:06] production.ERROR: exception 'Database\QueryException' with message 'SQLSTATE[42S22]: Column not found: 1054 Unknown column 'nova_family_tree_groups.treeID' in 'on clause' (SQL: select * from `nova_family_relation_joins` inner join `nova_users` on `nova_family_tree_groups`.`treeID` = `nova_user`.`family_id` where `nova_family_relation_joins`.`userID` = 1)' in C:\xampp\htdocs\trust\system\Database\Connection.php:548
Stack trace:
#0 C:\xampp\htdocs\trust\system\Database\Connection.php(517): Database\Connection->runQueryCallback('select * from `...', Array, Object(Closure))
#1 C:\xampp\htdocs\trust\system\Database\Connection.php(268): Database\Connection->run('select * from `...', Array, Object(Closure))
#2 C:\xampp\htdocs\trust\system\Database\Query\Builder.php(1334): Database\Connection->select('select * from `...', Array)
#3 C:\xampp\htdocs\trust\system\Database\Query\Builder.php(1324): Database\Query\Builder->runSelect()
#4 C:\xampp\htdocs\trust\system\Database\Query\Builder.php(1311): Database\Query\Builder->getFresh(Array)
#5 C:\xampp\htdocs\trust\app\Controllers\Admin\Family.php(31): Database\Query\Builder->get()
#6 [internal function]: App\Controllers\Admin\Family->index()
#7 C:\xampp\htdocs\trust\system\Routing\Controller.php(240): call_user_func_array(Array, Array)
#8 C:\xampp\htdocs\trust\system\Routing\ControllerDispatcher.php(91): Routing\Controller->callAction('index', Array)
#9 C:\xampp\htdocs\trust\system\Routing\ControllerDispatcher.php(60): Routing\ControllerDispatcher->call(Object(App\Controllers\Admin\Family), Object(Routing\Route), 'index')
#10 C:\xampp\htdocs\trust\system\Routing\Router.php(958): Routing\ControllerDispatcher->dispatch(Object(Routing\Route), Object(Http\Request), 'App\\Controllers...', 'index')
#11 [internal function]: Routing\Router->Routing\{closure}()
#12 C:\xampp\htdocs\trust\system\Routing\Route.php(128): call_user_func_array(Object(Closure), Array)
#13 C:\xampp\htdocs\trust\system\Routing\Router.php(1026): Routing\Route->run()
#14 C:\xampp\htdocs\trust\system\Routing\Router.php(994): Routing\Router->dispatchToRoute(Object(Http\Request))
#15 C:\xampp\htdocs\trust\system\Foundation\Application.php(744): Routing\Router->dispatch(Object(Http\Request))
#16 C:\xampp\htdocs\trust\system\Foundation\Application.php(717): Foundation\Application->dispatch(Object(Http\Request))
#17 C:\xampp\htdocs\trust\shared\Http\ContentGuard.php(62): Foundation\Application->handle(Object(Http\Request), 1, true)
#18 C:\xampp\htdocs\trust\system\Session\Middleware.php(77): Shared\Http\ContentGuard->handle(Object(Http\Request), 1, true)
#19 C:\xampp\htdocs\trust\system\Cookie\Queue.php(49): Session\Middleware->handle(Object(Http\Request), 1, true)
#20 C:\xampp\htdocs\trust\system\Cookie\Guard.php(54): Cookie\Queue->handle(Object(Http\Request), 1, true)
#21 C:\xampp\htdocs\trust\vendor\stack\builder\src\Stack\StackedHttpKernel.php(23): Cookie\Guard->handle(Object(Http\Request), 1, true)
#22 C:\xampp\htdocs\trust\system\Foundation\Application.php(615): Stack\StackedHttpKernel->handle(Object(Http\Request))
#23 C:\xampp\htdocs\trust\app\Boot\Start.php(244): Foundation\Application->run()
#24 C:\xampp\htdocs\trust\public\index.php(37): require('C:\\xampp\\htdocs...')
#25 {main} [] []
[2016-11-04 11:13:45] production.ERROR: exception 'Database\QueryException' with message 'SQLSTATE[42S22]: Column not found: 1054 Unknown column 'nova_family_tree_groups.treeID' in 'on clause' (SQL: select * from `nova_family_relation_joins` inner join `nova_users` on `nova_family_tree_groups`.`treeID` = `nova_user`.`family_id`)' in C:\xampp\htdocs\trust\system\Database\Connection.php:548
Stack trace:
#0 C:\xampp\htdocs\trust\system\Database\Connection.php(517): Database\Connection->runQueryCallback('select * from `...', Array, Object(Closure))
#1 C:\xampp\htdocs\trust\system\Database\Connection.php(268): Database\Connection->run('select * from `...', Array, Object(Closure))
#2 C:\xampp\htdocs\trust\system\Database\Query\Builder.php(1334): Database\Connection->select('select * from `...', Array)
#3 C:\xampp\htdocs\trust\system\Database\Query\Builder.php(1324): Database\Query\Builder->runSelect()
#4 C:\xampp\htdocs\trust\system\Database\Query\Builder.php(1311): Database\Query\Builder->getFresh(Array)
#5 C:\xampp\htdocs\trust\app\Controllers\Admin\Family.php(30): Database\Query\Builder->get()
#6 [internal function]: App\Controllers\Admin\Family->index()
#7 C:\xampp\htdocs\trust\system\Routing\Controller.php(240): call_user_func_array(Array, Array)
#8 C:\xampp\htdocs\trust\system\Routing\ControllerDispatcher.php(91): Routing\Controller->callAction('index', Array)
#9 C:\xampp\htdocs\trust\system\Routing\ControllerDispatcher.php(60): Routing\ControllerDispatcher->call(Object(App\Controllers\Admin\Family), Object(Routing\Route), 'index')
#10 C:\xampp\htdocs\trust\system\Routing\Router.php(958): Routing\ControllerDispatcher->dispatch(Object(Routing\Route), Object(Http\Request), 'App\\Controllers...', 'index')
#11 [internal function]: Routing\Router->Routing\{closure}()
#12 C:\xampp\htdocs\trust\system\Routing\Route.php(128): call_user_func_array(Object(Closure), Array)
#13 C:\xampp\htdocs\trust\system\Routing\Router.php(1026): Routing\Route->run()
#14 C:\xampp\htdocs\trust\system\Routing\Router.php(994): Routing\Router->dispatchToRoute(Object(Http\Request))
#15 C:\xampp\htdocs\trust\system\Foundation\Application.php(744): Routing\Router->dispatch(Object(Http\Request))
#16 C:\xampp\htdocs\trust\system\Foundation\Application.php(717): Foundation\Application->dispatch(Object(Http\Request))
#17 C:\xampp\htdocs\trust\shared\Http\ContentGuard.php(62): Foundation\Application->handle(Object(Http\Request), 1, true)
#18 C:\xampp\htdocs\trust\system\Session\Middleware.php(77): Shared\Http\ContentGuard->handle(Object(Http\Request), 1, true)
#19 C:\xampp\htdocs\trust\system\Cookie\Queue.php(49): Session\Middleware->handle(Object(Http\Request), 1, true)
#20 C:\xampp\htdocs\trust\system\Cookie\Guard.php(54): Cookie\Queue->handle(Object(Http\Request), 1, true)
#21 C:\xampp\htdocs\trust\vendor\stack\builder\src\Stack\StackedHttpKernel.php(23): Cookie\Guard->handle(Object(Http\Request), 1, true)
#22 C:\xampp\htdocs\trust\system\Foundation\Application.php(615): Stack\StackedHttpKernel->handle(Object(Http\Request))
#23 C:\xampp\htdocs\trust\app\Boot\Start.php(244): Foundation\Application->run()
#24 C:\xampp\htdocs\trust\public\index.php(37): require('C:\\xampp\\htdocs...')
#25 {main} [] []
[2016-11-04 11:14:02] production.ERROR: exception 'Database\QueryException' with message 'SQLSTATE[42S22]: Column not found: 1054 Unknown column 'nova_family_relation_joins.treeID' in 'on clause' (SQL: select * from `nova_family_relation_joins` inner join `nova_users` on `nova_family_relation_joins`.`treeID` = `nova_user`.`family_id`)' in C:\xampp\htdocs\trust\system\Database\Connection.php:548
Stack trace:
#0 C:\xampp\htdocs\trust\system\Database\Connection.php(517): Database\Connection->runQueryCallback('select * from `...', Array, Object(Closure))
#1 C:\xampp\htdocs\trust\system\Database\Connection.php(268): Database\Connection->run('select * from `...', Array, Object(Closure))
#2 C:\xampp\htdocs\trust\system\Database\Query\Builder.php(1334): Database\Connection->select('select * from `...', Array)
#3 C:\xampp\htdocs\trust\system\Database\Query\Builder.php(1324): Database\Query\Builder->runSelect()
#4 C:\xampp\htdocs\trust\system\Database\Query\Builder.php(1311): Database\Query\Builder->getFresh(Array)
#5 C:\xampp\htdocs\trust\app\Controllers\Admin\Family.php(30): Database\Query\Builder->get()
#6 [internal function]: App\Controllers\Admin\Family->index()
#7 C:\xampp\htdocs\trust\system\Routing\Controller.php(240): call_user_func_array(Array, Array)
#8 C:\xampp\htdocs\trust\system\Routing\ControllerDispatcher.php(91): Routing\Controller->callAction('index', Array)
#9 C:\xampp\htdocs\trust\system\Routing\ControllerDispatcher.php(60): Routing\ControllerDispatcher->call(Object(App\Controllers\Admin\Family), Object(Routing\Route), 'index')
#10 C:\xampp\htdocs\trust\system\Routing\Router.php(958): Routing\ControllerDispatcher->dispatch(Object(Routing\Route), Object(Http\Request), 'App\\Controllers...', 'index')
#11 [internal function]: Routing\Router->Routing\{closure}()
#12 C:\xampp\htdocs\trust\system\Routing\Route.php(128): call_user_func_array(Object(Closure), Array)
#13 C:\xampp\htdocs\trust\system\Routing\Router.php(1026): Routing\Route->run()
#14 C:\xampp\htdocs\trust\system\Routing\Router.php(994): Routing\Router->dispatchToRoute(Object(Http\Request))
#15 C:\xampp\htdocs\trust\system\Foundation\Application.php(744): Routing\Router->dispatch(Object(Http\Request))
#16 C:\xampp\htdocs\trust\system\Foundation\Application.php(717): Foundation\Application->dispatch(Object(Http\Request))
#17 C:\xampp\htdocs\trust\shared\Http\ContentGuard.php(62): Foundation\Application->handle(Object(Http\Request), 1, true)
#18 C:\xampp\htdocs\trust\system\Session\Middleware.php(77): Shared\Http\ContentGuard->handle(Object(Http\Request), 1, true)
#19 C:\xampp\htdocs\trust\system\Cookie\Queue.php(49): Session\Middleware->handle(Object(Http\Request), 1, true)
#20 C:\xampp\htdocs\trust\system\Cookie\Guard.php(54): Cookie\Queue->handle(Object(Http\Request), 1, true)
#21 C:\xampp\htdocs\trust\vendor\stack\builder\src\Stack\StackedHttpKernel.php(23): Cookie\Guard->handle(Object(Http\Request), 1, true)
#22 C:\xampp\htdocs\trust\system\Foundation\Application.php(615): Stack\StackedHttpKernel->handle(Object(Http\Request))
#23 C:\xampp\htdocs\trust\app\Boot\Start.php(244): Foundation\Application->run()
#24 C:\xampp\htdocs\trust\public\index.php(37): require('C:\\xampp\\htdocs...')
#25 {main} [] []
[2016-11-04 11:14:08] production.ERROR: exception 'Database\QueryException' with message 'SQLSTATE[42S22]: Column not found: 1054 Unknown column 'nova_family_relation_joins.treeID' in 'on clause' (SQL: select * from `nova_family_relation_joins` inner join `nova_users` on `nova_family_relation_joins`.`treeID` = `nova_user`.`family_id`)' in C:\xampp\htdocs\trust\system\Database\Connection.php:548
Stack trace:
#0 C:\xampp\htdocs\trust\system\Database\Connection.php(517): Database\Connection->runQueryCallback('select * from `...', Array, Object(Closure))
#1 C:\xampp\htdocs\trust\system\Database\Connection.php(268): Database\Connection->run('select * from `...', Array, Object(Closure))
#2 C:\xampp\htdocs\trust\system\Database\Query\Builder.php(1334): Database\Connection->select('select * from `...', Array)
#3 C:\xampp\htdocs\trust\system\Database\Query\Builder.php(1324): Database\Query\Builder->runSelect()
#4 C:\xampp\htdocs\trust\system\Database\Query\Builder.php(1311): Database\Query\Builder->getFresh(Array)
#5 C:\xampp\htdocs\trust\app\Controllers\Admin\Family.php(30): Database\Query\Builder->get()
#6 [internal function]: App\Controllers\Admin\Family->index()
#7 C:\xampp\htdocs\trust\system\Routing\Controller.php(240): call_user_func_array(Array, Array)
#8 C:\xampp\htdocs\trust\system\Routing\ControllerDispatcher.php(91): Routing\Controller->callAction('index', Array)
#9 C:\xampp\htdocs\trust\system\Routing\ControllerDispatcher.php(60): Routing\ControllerDispatcher->call(Object(App\Controllers\Admin\Family), Object(Routing\Route), 'index')
#10 C:\xampp\htdocs\trust\system\Routing\Router.php(958): Routing\ControllerDispatcher->dispatch(Object(Routing\Route), Object(Http\Request), 'App\\Controllers...', 'index')
#11 [internal function]: Routing\Router->Routing\{closure}()
#12 C:\xampp\htdocs\trust\system\Routing\Route.php(128): call_user_func_array(Object(Closure), Array)
#13 C:\xampp\htdocs\trust\system\Routing\Router.php(1026): Routing\Route->run()
#14 C:\xampp\htdocs\trust\system\Routing\Router.php(994): Routing\Router->dispatchToRoute(Object(Http\Request))
#15 C:\xampp\htdocs\trust\system\Foundation\Application.php(744): Routing\Router->dispatch(Object(Http\Request))
#16 C:\xampp\htdocs\trust\system\Foundation\Application.php(717): Foundation\Application->dispatch(Object(Http\Request))
#17 C:\xampp\htdocs\trust\shared\Http\ContentGuard.php(62): Foundation\Application->handle(Object(Http\Request), 1, true)
#18 C:\xampp\htdocs\trust\system\Session\Middleware.php(77): Shared\Http\ContentGuard->handle(Object(Http\Request), 1, true)
#19 C:\xampp\htdocs\trust\system\Cookie\Queue.php(49): Session\Middleware->handle(Object(Http\Request), 1, true)
#20 C:\xampp\htdocs\trust\system\Cookie\Guard.php(54): Cookie\Queue->handle(Object(Http\Request), 1, true)
#21 C:\xampp\htdocs\trust\vendor\stack\builder\src\Stack\StackedHttpKernel.php(23): Cookie\Guard->handle(Object(Http\Request), 1, true)
#22 C:\xampp\htdocs\trust\system\Foundation\Application.php(615): Stack\StackedHttpKernel->handle(Object(Http\Request))
#23 C:\xampp\htdocs\trust\app\Boot\Start.php(244): Foundation\Application->run()
#24 C:\xampp\htdocs\trust\public\index.php(37): require('C:\\xampp\\htdocs...')
#25 {main} [] []
[2016-11-04 11:14:41] production.ERROR: exception 'Database\QueryException' with message 'SQLSTATE[42S22]: Column not found: 1054 Unknown column 'nova_user.family_id' in 'on clause' (SQL: select * from `nova_family_relation_joins` inner join `nova_users` on `nova_family_relation_joins`.`family_id` = `nova_user`.`family_id`)' in C:\xampp\htdocs\trust\system\Database\Connection.php:548
Stack trace:
#0 C:\xampp\htdocs\trust\system\Database\Connection.php(517): Database\Connection->runQueryCallback('select * from `...', Array, Object(Closure))
#1 C:\xampp\htdocs\trust\system\Database\Connection.php(268): Database\Connection->run('select * from `...', Array, Object(Closure))
#2 C:\xampp\htdocs\trust\system\Database\Query\Builder.php(1334): Database\Connection->select('select * from `...', Array)
#3 C:\xampp\htdocs\trust\system\Database\Query\Builder.php(1324): Database\Query\Builder->runSelect()
#4 C:\xampp\htdocs\trust\system\Database\Query\Builder.php(1311): Database\Query\Builder->getFresh(Array)
#5 C:\xampp\htdocs\trust\app\Controllers\Admin\Family.php(30): Database\Query\Builder->get()
#6 [internal function]: App\Controllers\Admin\Family->index()
#7 C:\xampp\htdocs\trust\system\Routing\Controller.php(240): call_user_func_array(Array, Array)
#8 C:\xampp\htdocs\trust\system\Routing\ControllerDispatcher.php(91): Routing\Controller->callAction('index', Array)
#9 C:\xampp\htdocs\trust\system\Routing\ControllerDispatcher.php(60): Routing\ControllerDispatcher->call(Object(App\Controllers\Admin\Family), Object(Routing\Route), 'index')
#10 C:\xampp\htdocs\trust\system\Routing\Router.php(958): Routing\ControllerDispatcher->dispatch(Object(Routing\Route), Object(Http\Request), 'App\\Controllers...', 'index')
#11 [internal function]: Routing\Router->Routing\{closure}()
#12 C:\xampp\htdocs\trust\system\Routing\Route.php(128): call_user_func_array(Object(Closure), Array)
#13 C:\xampp\htdocs\trust\system\Routing\Router.php(1026): Routing\Route->run()
#14 C:\xampp\htdocs\trust\system\Routing\Router.php(994): Routing\Router->dispatchToRoute(Object(Http\Request))
#15 C:\xampp\htdocs\trust\system\Foundation\Application.php(744): Routing\Router->dispatch(Object(Http\Request))
#16 C:\xampp\htdocs\trust\system\Foundation\Application.php(717): Foundation\Application->dispatch(Object(Http\Request))
#17 C:\xampp\htdocs\trust\shared\Http\ContentGuard.php(62): Foundation\Application->handle(Object(Http\Request), 1, true)
#18 C:\xampp\htdocs\trust\system\Session\Middleware.php(77): Shared\Http\ContentGuard->handle(Object(Http\Request), 1, true)
#19 C:\xampp\htdocs\trust\system\Cookie\Queue.php(49): Session\Middleware->handle(Object(Http\Request), 1, true)
#20 C:\xampp\htdocs\trust\system\Cookie\Guard.php(54): Cookie\Queue->handle(Object(Http\Request), 1, true)
#21 C:\xampp\htdocs\trust\vendor\stack\builder\src\Stack\StackedHttpKernel.php(23): Cookie\Guard->handle(Object(Http\Request), 1, true)
#22 C:\xampp\htdocs\trust\system\Foundation\Application.php(615): Stack\StackedHttpKernel->handle(Object(Http\Request))
#23 C:\xampp\htdocs\trust\app\Boot\Start.php(244): Foundation\Application->run()
#24 C:\xampp\htdocs\trust\public\index.php(37): require('C:\\xampp\\htdocs...')
#25 {main} [] []
[2016-11-04 11:34:29] production.ERROR: exception 'Database\QueryException' with message 'SQLSTATE[42000]: Syntax error or access violation: 1066 Not unique table/alias: 'nova_users' (SQL: select `nova_users`.`username`, `nova_family_relation_joins`.`secondUserID`, `nova_family_relations`.`name_relation` from `nova_users` inner join `nova_family_tree_groups` on `nova_users`.`family_id` = `nova_family_tree_groups`.`treeID` inner join `nova_family_relation_joins` on `nova_users`.`family_id` = `nova_family_relation_joins`.`family_id` inner join `nova_family_relations` on `nova_family_relation_joins`.`relationID` = `nova_family_relations`.`id` left join `nova_users` on `nova_family_relation_joins`.`secondUserID` = `nova_users`.`id` where `nova_users`.`family_id` = 1)' in C:\xampp\htdocs\trust\system\Database\Connection.php:548
Stack trace:
#0 C:\xampp\htdocs\trust\system\Database\Connection.php(517): Database\Connection->runQueryCallback('select `nova_us...', Array, Object(Closure))
#1 C:\xampp\htdocs\trust\system\Database\Connection.php(268): Database\Connection->run('select `nova_us...', Array, Object(Closure))
#2 C:\xampp\htdocs\trust\system\Database\Query\Builder.php(1334): Database\Connection->select('select `nova_us...', Array)
#3 C:\xampp\htdocs\trust\system\Database\Query\Builder.php(1324): Database\Query\Builder->runSelect()
#4 C:\xampp\htdocs\trust\system\Database\Query\Builder.php(1311): Database\Query\Builder->getFresh(Array)
#5 C:\xampp\htdocs\trust\app\Controllers\Admin\Family.php(35): Database\Query\Builder->get()
#6 [internal function]: App\Controllers\Admin\Family->index()
#7 C:\xampp\htdocs\trust\system\Routing\Controller.php(240): call_user_func_array(Array, Array)
#8 C:\xampp\htdocs\trust\system\Routing\ControllerDispatcher.php(91): Routing\Controller->callAction('index', Array)
#9 C:\xampp\htdocs\trust\system\Routing\ControllerDispatcher.php(60): Routing\ControllerDispatcher->call(Object(App\Controllers\Admin\Family), Object(Routing\Route), 'index')
#10 C:\xampp\htdocs\trust\system\Routing\Router.php(958): Routing\ControllerDispatcher->dispatch(Object(Routing\Route), Object(Http\Request), 'App\\Controllers...', 'index')
#11 [internal function]: Routing\Router->Routing\{closure}()
#12 C:\xampp\htdocs\trust\system\Routing\Route.php(128): call_user_func_array(Object(Closure), Array)
#13 C:\xampp\htdocs\trust\system\Routing\Router.php(1026): Routing\Route->run()
#14 C:\xampp\htdocs\trust\system\Routing\Router.php(994): Routing\Router->dispatchToRoute(Object(Http\Request))
#15 C:\xampp\htdocs\trust\system\Foundation\Application.php(744): Routing\Router->dispatch(Object(Http\Request))
#16 C:\xampp\htdocs\trust\system\Foundation\Application.php(717): Foundation\Application->dispatch(Object(Http\Request))
#17 C:\xampp\htdocs\trust\shared\Http\ContentGuard.php(62): Foundation\Application->handle(Object(Http\Request), 1, true)
#18 C:\xampp\htdocs\trust\system\Session\Middleware.php(77): Shared\Http\ContentGuard->handle(Object(Http\Request), 1, true)
#19 C:\xampp\htdocs\trust\system\Cookie\Queue.php(49): Session\Middleware->handle(Object(Http\Request), 1, true)
#20 C:\xampp\htdocs\trust\system\Cookie\Guard.php(54): Cookie\Queue->handle(Object(Http\Request), 1, true)
#21 C:\xampp\htdocs\trust\vendor\stack\builder\src\Stack\StackedHttpKernel.php(23): Cookie\Guard->handle(Object(Http\Request), 1, true)
#22 C:\xampp\htdocs\trust\system\Foundation\Application.php(615): Stack\StackedHttpKernel->handle(Object(Http\Request))
#23 C:\xampp\htdocs\trust\app\Boot\Start.php(244): Foundation\Application->run()
#24 C:\xampp\htdocs\trust\public\index.php(37): require('C:\\xampp\\htdocs...')
#25 {main} [] []
[2016-11-04 11:38:59] production.ERROR: exception 'ErrorException' with message 'Trying to get property of non-object' in C:\xampp\htdocs\trust\app\Controllers\Admin\Family.php:38
Stack trace:
#0 C:\xampp\htdocs\trust\app\Controllers\Admin\Family.php(38): Exception\Handler->handleError(8, 'Trying to get p...', 'C:\\xampp\\htdocs...', 38, Array)
#1 [internal function]: App\Controllers\Admin\Family->index()
#2 C:\xampp\htdocs\trust\system\Routing\Controller.php(240): call_user_func_array(Array, Array)
#3 C:\xampp\htdocs\trust\system\Routing\ControllerDispatcher.php(91): Routing\Controller->callAction('index', Array)
#4 C:\xampp\htdocs\trust\system\Routing\ControllerDispatcher.php(60): Routing\ControllerDispatcher->call(Object(App\Controllers\Admin\Family), Object(Routing\Route), 'index')
#5 C:\xampp\htdocs\trust\system\Routing\Router.php(958): Routing\ControllerDispatcher->dispatch(Object(Routing\Route), Object(Http\Request), 'App\\Controllers...', 'index')
#6 [internal function]: Routing\Router->Routing\{closure}()
#7 C:\xampp\htdocs\trust\system\Routing\Route.php(128): call_user_func_array(Object(Closure), Array)
#8 C:\xampp\htdocs\trust\system\Routing\Router.php(1026): Routing\Route->run()
#9 C:\xampp\htdocs\trust\system\Routing\Router.php(994): Routing\Router->dispatchToRoute(Object(Http\Request))
#10 C:\xampp\htdocs\trust\system\Foundation\Application.php(744): Routing\Router->dispatch(Object(Http\Request))
#11 C:\xampp\htdocs\trust\system\Foundation\Application.php(717): Foundation\Application->dispatch(Object(Http\Request))
#12 C:\xampp\htdocs\trust\shared\Http\ContentGuard.php(62): Foundation\Application->handle(Object(Http\Request), 1, true)
#13 C:\xampp\htdocs\trust\system\Session\Middleware.php(77): Shared\Http\ContentGuard->handle(Object(Http\Request), 1, true)
#14 C:\xampp\htdocs\trust\system\Cookie\Queue.php(49): Session\Middleware->handle(Object(Http\Request), 1, true)
#15 C:\xampp\htdocs\trust\system\Cookie\Guard.php(54): Cookie\Queue->handle(Object(Http\Request), 1, true)
#16 C:\xampp\htdocs\trust\vendor\stack\builder\src\Stack\StackedHttpKernel.php(23): Cookie\Guard->handle(Object(Http\Request), 1, true)
#17 C:\xampp\htdocs\trust\system\Foundation\Application.php(615): Stack\StackedHttpKernel->handle(Object(Http\Request))
#18 C:\xampp\htdocs\trust\app\Boot\Start.php(244): Foundation\Application->run()
#19 C:\xampp\htdocs\trust\public\index.php(37): require('C:\\xampp\\htdocs...')
#20 {main} [] []
[2016-11-04 11:39:32] production.ERROR: exception 'ErrorException' with message 'Undefined index: secondUserID' in C:\xampp\htdocs\trust\app\Controllers\Admin\Family.php:38
Stack trace:
#0 C:\xampp\htdocs\trust\app\Controllers\Admin\Family.php(38): Exception\Handler->handleError(8, 'Undefined index...', 'C:\\xampp\\htdocs...', 38, Array)
#1 [internal function]: App\Controllers\Admin\Family->index()
#2 C:\xampp\htdocs\trust\system\Routing\Controller.php(240): call_user_func_array(Array, Array)
#3 C:\xampp\htdocs\trust\system\Routing\ControllerDispatcher.php(91): Routing\Controller->callAction('index', Array)
#4 C:\xampp\htdocs\trust\system\Routing\ControllerDispatcher.php(60): Routing\ControllerDispatcher->call(Object(App\Controllers\Admin\Family), Object(Routing\Route), 'index')
#5 C:\xampp\htdocs\trust\system\Routing\Router.php(958): Routing\ControllerDispatcher->dispatch(Object(Routing\Route), Object(Http\Request), 'App\\Controllers...', 'index')
#6 [internal function]: Routing\Router->Routing\{closure}()
#7 C:\xampp\htdocs\trust\system\Routing\Route.php(128): call_user_func_array(Object(Closure), Array)
#8 C:\xampp\htdocs\trust\system\Routing\Router.php(1026): Routing\Route->run()
#9 C:\xampp\htdocs\trust\system\Routing\Router.php(994): Routing\Router->dispatchToRoute(Object(Http\Request))
#10 C:\xampp\htdocs\trust\system\Foundation\Application.php(744): Routing\Router->dispatch(Object(Http\Request))
#11 C:\xampp\htdocs\trust\system\Foundation\Application.php(717): Foundation\Application->dispatch(Object(Http\Request))
#12 C:\xampp\htdocs\trust\shared\Http\ContentGuard.php(62): Foundation\Application->handle(Object(Http\Request), 1, true)
#13 C:\xampp\htdocs\trust\system\Session\Middleware.php(77): Shared\Http\ContentGuard->handle(Object(Http\Request), 1, true)
#14 C:\xampp\htdocs\trust\system\Cookie\Queue.php(49): Session\Middleware->handle(Object(Http\Request), 1, true)
#15 C:\xampp\htdocs\trust\system\Cookie\Guard.php(54): Cookie\Queue->handle(Object(Http\Request), 1, true)
#16 C:\xampp\htdocs\trust\vendor\stack\builder\src\Stack\StackedHttpKernel.php(23): Cookie\Guard->handle(Object(Http\Request), 1, true)
#17 C:\xampp\htdocs\trust\system\Foundation\Application.php(615): Stack\StackedHttpKernel->handle(Object(Http\Request))
#18 C:\xampp\htdocs\trust\app\Boot\Start.php(244): Foundation\Application->run()
#19 C:\xampp\htdocs\trust\public\index.php(37): require('C:\\xampp\\htdocs...')
#20 {main} [] []
[2016-11-04 11:42:10] production.ERROR: exception 'ErrorException' with message 'Trying to get property of non-object' in C:\xampp\htdocs\trust\app\Controllers\Admin\Family.php:38
Stack trace:
#0 C:\xampp\htdocs\trust\app\Controllers\Admin\Family.php(38): Exception\Handler->handleError(8, 'Trying to get p...', 'C:\\xampp\\htdocs...', 38, Array)
#1 [internal function]: App\Controllers\Admin\Family->index()
#2 C:\xampp\htdocs\trust\system\Routing\Controller.php(240): call_user_func_array(Array, Array)
#3 C:\xampp\htdocs\trust\system\Routing\ControllerDispatcher.php(91): Routing\Controller->callAction('index', Array)
#4 C:\xampp\htdocs\trust\system\Routing\ControllerDispatcher.php(60): Routing\ControllerDispatcher->call(Object(App\Controllers\Admin\Family), Object(Routing\Route), 'index')
#5 C:\xampp\htdocs\trust\system\Routing\Router.php(958): Routing\ControllerDispatcher->dispatch(Object(Routing\Route), Object(Http\Request), 'App\\Controllers...', 'index')
#6 [internal function]: Routing\Router->Routing\{closure}()
#7 C:\xampp\htdocs\trust\system\Routing\Route.php(128): call_user_func_array(Object(Closure), Array)
#8 C:\xampp\htdocs\trust\system\Routing\Router.php(1026): Routing\Route->run()
#9 C:\xampp\htdocs\trust\system\Routing\Router.php(994): Routing\Router->dispatchToRoute(Object(Http\Request))
#10 C:\xampp\htdocs\trust\system\Foundation\Application.php(744): Routing\Router->dispatch(Object(Http\Request))
#11 C:\xampp\htdocs\trust\system\Foundation\Application.php(717): Foundation\Application->dispatch(Object(Http\Request))
#12 C:\xampp\htdocs\trust\shared\Http\ContentGuard.php(62): Foundation\Application->handle(Object(Http\Request), 1, true)
#13 C:\xampp\htdocs\trust\system\Session\Middleware.php(77): Shared\Http\ContentGuard->handle(Object(Http\Request), 1, true)
#14 C:\xampp\htdocs\trust\system\Cookie\Queue.php(49): Session\Middleware->handle(Object(Http\Request), 1, true)
#15 C:\xampp\htdocs\trust\system\Cookie\Guard.php(54): Cookie\Queue->handle(Object(Http\Request), 1, true)
#16 C:\xampp\htdocs\trust\vendor\stack\builder\src\Stack\StackedHttpKernel.php(23): Cookie\Guard->handle(Object(Http\Request), 1, true)
#17 C:\xampp\htdocs\trust\system\Foundation\Application.php(615): Stack\StackedHttpKernel->handle(Object(Http\Request))
#18 C:\xampp\htdocs\trust\app\Boot\Start.php(244): Foundation\Application->run()
#19 C:\xampp\htdocs\trust\public\index.php(37): require('C:\\xampp\\htdocs...')
#20 {main} [] []
[2016-11-04 11:42:46] production.ERROR: exception 'ErrorException' with message 'Trying to get property of non-object' in C:\xampp\htdocs\trust\app\Controllers\Admin\Family.php:36
Stack trace:
#0 C:\xampp\htdocs\trust\app\Controllers\Admin\Family.php(36): Exception\Handler->handleError(8, 'Trying to get p...', 'C:\\xampp\\htdocs...', 36, Array)
#1 [internal function]: App\Controllers\Admin\Family->index()
#2 C:\xampp\htdocs\trust\system\Routing\Controller.php(240): call_user_func_array(Array, Array)
#3 C:\xampp\htdocs\trust\system\Routing\ControllerDispatcher.php(91): Routing\Controller->callAction('index', Array)
#4 C:\xampp\htdocs\trust\system\Routing\ControllerDispatcher.php(60): Routing\ControllerDispatcher->call(Object(App\Controllers\Admin\Family), Object(Routing\Route), 'index')
#5 C:\xampp\htdocs\trust\system\Routing\Router.php(958): Routing\ControllerDispatcher->dispatch(Object(Routing\Route), Object(Http\Request), 'App\\Controllers...', 'index')
#6 [internal function]: Routing\Router->Routing\{closure}()
#7 C:\xampp\htdocs\trust\system\Routing\Route.php(128): call_user_func_array(Object(Closure), Array)
#8 C:\xampp\htdocs\trust\system\Routing\Router.php(1026): Routing\Route->run()
#9 C:\xampp\htdocs\trust\system\Routing\Router.php(994): Routing\Router->dispatchToRoute(Object(Http\Request))
#10 C:\xampp\htdocs\trust\system\Foundation\Application.php(744): Routing\Router->dispatch(Object(Http\Request))
#11 C:\xampp\htdocs\trust\system\Foundation\Application.php(717): Foundation\Application->dispatch(Object(Http\Request))
#12 C:\xampp\htdocs\trust\shared\Http\ContentGuard.php(62): Foundation\Application->handle(Object(Http\Request), 1, true)
#13 C:\xampp\htdocs\trust\system\Session\Middleware.php(77): Shared\Http\ContentGuard->handle(Object(Http\Request), 1, true)
#14 C:\xampp\htdocs\trust\system\Cookie\Queue.php(49): Session\Middleware->handle(Object(Http\Request), 1, true)
#15 C:\xampp\htdocs\trust\system\Cookie\Guard.php(54): Cookie\Queue->handle(Object(Http\Request), 1, true)
#16 C:\xampp\htdocs\trust\vendor\stack\builder\src\Stack\StackedHttpKernel.php(23): Cookie\Guard->handle(Object(Http\Request), 1, true)
#17 C:\xampp\htdocs\trust\system\Foundation\Application.php(615): Stack\StackedHttpKernel->handle(Object(Http\Request))
#18 C:\xampp\htdocs\trust\app\Boot\Start.php(244): Foundation\Application->run()
#19 C:\xampp\htdocs\trust\public\index.php(37): require('C:\\xampp\\htdocs...')
#20 {main} [] []
[2016-11-04 11:43:07] production.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected ''secondUserID'' (T_CONSTANT_ENCAPSED_STRING), expecting identifier (T_STRING) or variable (T_VARIABLE) or '{' or '$'' in C:\xampp\htdocs\trust\app\Controllers\Admin\Family.php:36
Stack trace:
#0 [internal function]: Exception\Handler->handleShutdown()
#1 {main} [] []
[2016-11-04 11:43:56] production.ERROR: exception 'ErrorException' with message 'Undefined variable: secondUserID' in C:\xampp\htdocs\trust\app\Controllers\Admin\Family.php:36
Stack trace:
#0 C:\xampp\htdocs\trust\app\Controllers\Admin\Family.php(36): Exception\Handler->handleError(8, 'Undefined varia...', 'C:\\xampp\\htdocs...', 36, Array)
#1 [internal function]: App\Controllers\Admin\Family->index()
#2 C:\xampp\htdocs\trust\system\Routing\Controller.php(240): call_user_func_array(Array, Array)
#3 C:\xampp\htdocs\trust\system\Routing\ControllerDispatcher.php(91): Routing\Controller->callAction('index', Array)
#4 C:\xampp\htdocs\trust\system\Routing\ControllerDispatcher.php(60): Routing\ControllerDispatcher->call(Object(App\Controllers\Admin\Family), Object(Routing\Route), 'index')
#5 C:\xampp\htdocs\trust\system\Routing\Router.php(958): Routing\ControllerDispatcher->dispatch(Object(Routing\Route), Object(Http\Request), 'App\\Controllers...', 'index')
#6 [internal function]: Routing\Router->Routing\{closure}()
#7 C:\xampp\htdocs\trust\system\Routing\Route.php(128): call_user_func_array(Object(Closure), Array)
#8 C:\xampp\htdocs\trust\system\Routing\Router.php(1026): Routing\Route->run()
#9 C:\xampp\htdocs\trust\system\Routing\Router.php(994): Routing\Router->dispatchToRoute(Object(Http\Request))
#10 C:\xampp\htdocs\trust\system\Foundation\Application.php(744): Routing\Router->dispatch(Object(Http\Request))
#11 C:\xampp\htdocs\trust\system\Foundation\Application.php(717): Foundation\Application->dispatch(Object(Http\Request))
#12 C:\xampp\htdocs\trust\shared\Http\ContentGuard.php(62): Foundation\Application->handle(Object(Http\Request), 1, true)
#13 C:\xampp\htdocs\trust\system\Session\Middleware.php(77): Shared\Http\ContentGuard->handle(Object(Http\Request), 1, true)
#14 C:\xampp\htdocs\trust\system\Cookie\Queue.php(49): Session\Middleware->handle(Object(Http\Request), 1, true)
#15 C:\xampp\htdocs\trust\system\Cookie\Guard.php(54): Cookie\Queue->handle(Object(Http\Request), 1, true)
#16 C:\xampp\htdocs\trust\vendor\stack\builder\src\Stack\StackedHttpKernel.php(23): Cookie\Guard->handle(Object(Http\Request), 1, true)
#17 C:\xampp\htdocs\trust\system\Foundation\Application.php(615): Stack\StackedHttpKernel->handle(Object(Http\Request))
#18 C:\xampp\htdocs\trust\app\Boot\Start.php(244): Foundation\Application->run()
#19 C:\xampp\htdocs\trust\public\index.php(37): require('C:\\xampp\\htdocs...')
#20 {main} [] []
[2016-11-04 11:49:22] production.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected '}'' in C:\xampp\htdocs\trust\app\Controllers\Admin\Family.php:48
Stack trace:
#0 [internal function]: Exception\Handler->handleShutdown()
#1 {main} [] []
[2016-11-04 11:49:35] production.ERROR: exception 'ErrorException' with message 'Array to string conversion' in C:\xampp\htdocs\trust\app\Views\Admin\Family\index.php:16
Stack trace:
#0 C:\xampp\htdocs\trust\app\Views\Admin\Family\index.php(16): Exception\Handler->handleError(8, 'Array to string...', 'C:\\xampp\\htdocs...', 16, Array)
#1 C:\xampp\htdocs\trust\system\View\Engines\PhpEngine.php(56): include('C:\\xampp\\htdocs...')
#2 C:\xampp\htdocs\trust\system\View\Engines\PhpEngine.php(31): View\Engines\PhpEngine->evaluatePath('C:\\xampp\\htdocs...', Array)
#3 C:\xampp\htdocs\trust\system\View\View.php(96): View\Engines\PhpEngine->get('C:\\xampp\\htdocs...', Array)
#4 C:\xampp\htdocs\trust\system\View\View.php(82): View\View->renderContents()
#5 C:\xampp\htdocs\trust\system\View\View.php(111): View\View->render()
#6 C:\xampp\htdocs\trust\system\View\View.php(96): View\View->gatherData()
#7 C:\xampp\htdocs\trust\system\View\View.php(82): View\View->renderContents()
#8 C:\xampp\htdocs\trust\app\Core\Controller.php(70): View\View->render()
#9 C:\xampp\htdocs\trust\system\Routing\Controller.php(250): App\Core\Controller->processResponse(Object(View\View))
#10 C:\xampp\htdocs\trust\system\Routing\ControllerDispatcher.php(91): Routing\Controller->callAction('index', Array)
#11 C:\xampp\htdocs\trust\system\Routing\ControllerDispatcher.php(60): Routing\ControllerDispatcher->call(Object(App\Controllers\Admin\Family), Object(Routing\Route), 'index')
#12 C:\xampp\htdocs\trust\system\Routing\Router.php(958): Routing\ControllerDispatcher->dispatch(Object(Routing\Route), Object(Http\Request), 'App\\Controllers...', 'index')
#13 [internal function]: Routing\Router->Routing\{closure}()
#14 C:\xampp\htdocs\trust\system\Routing\Route.php(128): call_user_func_array(Object(Closure), Array)
#15 C:\xampp\htdocs\trust\system\Routing\Router.php(1026): Routing\Route->run()
#16 C:\xampp\htdocs\trust\system\Routing\Router.php(994): Routing\Router->dispatchToRoute(Object(Http\Request))
#17 C:\xampp\htdocs\trust\system\Foundation\Application.php(744): Routing\Router->dispatch(Object(Http\Request))
#18 C:\xampp\htdocs\trust\system\Foundation\Application.php(717): Foundation\Application->dispatch(Object(Http\Request))
#19 C:\xampp\htdocs\trust\shared\Http\ContentGuard.php(62): Foundation\Application->handle(Object(Http\Request), 1, true)
#20 C:\xampp\htdocs\trust\system\Session\Middleware.php(77): Shared\Http\ContentGuard->handle(Object(Http\Request), 1, true)
#21 C:\xampp\htdocs\trust\system\Cookie\Queue.php(49): Session\Middleware->handle(Object(Http\Request), 1, true)
#22 C:\xampp\htdocs\trust\system\Cookie\Guard.php(54): Cookie\Queue->handle(Object(Http\Request), 1, true)
#23 C:\xampp\htdocs\trust\vendor\stack\builder\src\Stack\StackedHttpKernel.php(23): Cookie\Guard->handle(Object(Http\Request), 1, true)
#24 C:\xampp\htdocs\trust\system\Foundation\Application.php(615): Stack\StackedHttpKernel->handle(Object(Http\Request))
#25 C:\xampp\htdocs\trust\app\Boot\Start.php(244): Foundation\Application->run()
#26 C:\xampp\htdocs\trust\public\index.php(37): require('C:\\xampp\\htdocs...')
#27 {main} [] []
[2016-11-04 11:49:58] production.ERROR: exception 'ErrorException' with message 'Array to string conversion' in C:\xampp\htdocs\trust\app\Views\Admin\Family\index.php:16
Stack trace:
#0 C:\xampp\htdocs\trust\app\Views\Admin\Family\index.php(16): Exception\Handler->handleError(8, 'Array to string...', 'C:\\xampp\\htdocs...', 16, Array)
#1 C:\xampp\htdocs\trust\system\View\Engines\PhpEngine.php(56): include('C:\\xampp\\htdocs...')
#2 C:\xampp\htdocs\trust\system\View\Engines\PhpEngine.php(31): View\Engines\PhpEngine->evaluatePath('C:\\xampp\\htdocs...', Array)
#3 C:\xampp\htdocs\trust\system\View\View.php(96): View\Engines\PhpEngine->get('C:\\xampp\\htdocs...', Array)
#4 C:\xampp\htdocs\trust\system\View\View.php(82): View\View->renderContents()
#5 C:\xampp\htdocs\trust\system\View\View.php(111): View\View->render()
#6 C:\xampp\htdocs\trust\system\View\View.php(96): View\View->gatherData()
#7 C:\xampp\htdocs\trust\system\View\View.php(82): View\View->renderContents()
#8 C:\xampp\htdocs\trust\app\Core\Controller.php(70): View\View->render()
#9 C:\xampp\htdocs\trust\system\Routing\Controller.php(250): App\Core\Controller->processResponse(Object(View\View))
#10 C:\xampp\htdocs\trust\system\Routing\ControllerDispatcher.php(91): Routing\Controller->callAction('index', Array)
#11 C:\xampp\htdocs\trust\system\Routing\ControllerDispatcher.php(60): Routing\ControllerDispatcher->call(Object(App\Controllers\Admin\Family), Object(Routing\Route), 'index')
#12 C:\xampp\htdocs\trust\system\Routing\Router.php(958): Routing\ControllerDispatcher->dispatch(Object(Routing\Route), Object(Http\Request), 'App\\Controllers...', 'index')
#13 [internal function]: Routing\Router->Routing\{closure}()
#14 C:\xampp\htdocs\trust\system\Routing\Route.php(128): call_user_func_array(Object(Closure), Array)
#15 C:\xampp\htdocs\trust\system\Routing\Router.php(1026): Routing\Route->run()
#16 C:\xampp\htdocs\trust\system\Routing\Router.php(994): Routing\Router->dispatchToRoute(Object(Http\Request))
#17 C:\xampp\htdocs\trust\system\Foundation\Application.php(744): Routing\Router->dispatch(Object(Http\Request))
#18 C:\xampp\htdocs\trust\system\Foundation\Application.php(717): Foundation\Application->dispatch(Object(Http\Request))
#19 C:\xampp\htdocs\trust\shared\Http\ContentGuard.php(62): Foundation\Application->handle(Object(Http\Request), 1, true)
#20 C:\xampp\htdocs\trust\system\Session\Middleware.php(77): Shared\Http\ContentGuard->handle(Object(Http\Request), 1, true)
#21 C:\xampp\htdocs\trust\system\Cookie\Queue.php(49): Session\Middleware->handle(Object(Http\Request), 1, true)
#22 C:\xampp\htdocs\trust\system\Cookie\Guard.php(54): Cookie\Queue->handle(Object(Http\Request), 1, true)
#23 C:\xampp\htdocs\trust\vendor\stack\builder\src\Stack\StackedHttpKernel.php(23): Cookie\Guard->handle(Object(Http\Request), 1, true)
#24 C:\xampp\htdocs\trust\system\Foundation\Application.php(615): Stack\StackedHttpKernel->handle(Object(Http\Request))
#25 C:\xampp\htdocs\trust\app\Boot\Start.php(244): Foundation\Application->run()
#26 C:\xampp\htdocs\trust\public\index.php(37): require('C:\\xampp\\htdocs...')
#27 {main} [] []
[2016-11-04 12:09:02] production.ERROR: exception 'Database\QueryException' with message 'SQLSTATE[42S22]: Column not found: 1054 Unknown column '4' in 'group statement' (SQL: select `nova_users`.`username`, `nova_family_relation_joins`.`secondUserID`, `nova_family_relations`.`name_relation` from `nova_users` inner join `nova_family_tree_groups` on `nova_users`.`family_id` = `nova_family_tree_groups`.`treeID` inner join `nova_family_relation_joins` on `nova_users`.`family_id` = `nova_family_relation_joins`.`family_id` inner join `nova_family_relations` on `nova_family_relation_joins`.`relationID` = `nova_family_relations`.`id` where `nova_users`.`family_id` = 1 group by `4`)' in C:\xampp\htdocs\trust\system\Database\Connection.php:548
Stack trace:
#0 C:\xampp\htdocs\trust\system\Database\Connection.php(517): Database\Connection->runQueryCallback('select `nova_us...', Array, Object(Closure))
#1 C:\xampp\htdocs\trust\system\Database\Connection.php(268): Database\Connection->run('select `nova_us...', Array, Object(Closure))
#2 C:\xampp\htdocs\trust\system\Database\Query\Builder.php(1334): Database\Connection->select('select `nova_us...', Array)
#3 C:\xampp\htdocs\trust\system\Database\Query\Builder.php(1324): Database\Query\Builder->runSelect()
#4 C:\xampp\htdocs\trust\system\Database\Query\Builder.php(1311): Database\Query\Builder->getFresh(Array)
#5 C:\xampp\htdocs\trust\app\Controllers\Admin\Family.php(35): Database\Query\Builder->get()
#6 [internal function]: App\Controllers\Admin\Family->index()
#7 C:\xampp\htdocs\trust\system\Routing\Controller.php(240): call_user_func_array(Array, Array)
#8 C:\xampp\htdocs\trust\system\Routing\ControllerDispatcher.php(91): Routing\Controller->callAction('index', Array)
#9 C:\xampp\htdocs\trust\system\Routing\ControllerDispatcher.php(60): Routing\ControllerDispatcher->call(Object(App\Controllers\Admin\Family), Object(Routing\Route), 'index')
#10 C:\xampp\htdocs\trust\system\Routing\Router.php(958): Routing\ControllerDispatcher->dispatch(Object(Routing\Route), Object(Http\Request), 'App\\Controllers...', 'index')
#11 [internal function]: Routing\Router->Routing\{closure}()
#12 C:\xampp\htdocs\trust\system\Routing\Route.php(128): call_user_func_array(Object(Closure), Array)
#13 C:\xampp\htdocs\trust\system\Routing\Router.php(1026): Routing\Route->run()
#14 C:\xampp\htdocs\trust\system\Routing\Router.php(994): Routing\Router->dispatchToRoute(Object(Http\Request))
#15 C:\xampp\htdocs\trust\system\Foundation\Application.php(744): Routing\Router->dispatch(Object(Http\Request))
#16 C:\xampp\htdocs\trust\system\Foundation\Application.php(717): Foundation\Application->dispatch(Object(Http\Request))
#17 C:\xampp\htdocs\trust\shared\Http\ContentGuard.php(62): Foundation\Application->handle(Object(Http\Request), 1, true)
#18 C:\xampp\htdocs\trust\system\Session\Middleware.php(77): Shared\Http\ContentGuard->handle(Object(Http\Request), 1, true)
#19 C:\xampp\htdocs\trust\system\Cookie\Queue.php(49): Session\Middleware->handle(Object(Http\Request), 1, true)
#20 C:\xampp\htdocs\trust\system\Cookie\Guard.php(54): Cookie\Queue->handle(Object(Http\Request), 1, true)
#21 C:\xampp\htdocs\trust\vendor\stack\builder\src\Stack\StackedHttpKernel.php(23): Cookie\Guard->handle(Object(Http\Request), 1, true)
#22 C:\xampp\htdocs\trust\system\Foundation\Application.php(615): Stack\StackedHttpKernel->handle(Object(Http\Request))
#23 C:\xampp\htdocs\trust\app\Boot\Start.php(244): Foundation\Application->run()
#24 C:\xampp\htdocs\trust\public\index.php(37): require('C:\\xampp\\htdocs...')
#25 {main} [] []
[2016-11-04 12:16:01] production.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Class 'App\Controllers\Admin\ArrayObject' not found' in C:\xampp\htdocs\trust\app\Controllers\Admin\Family.php:39
Stack trace:
#0 [internal function]: Exception\Handler->handleShutdown()
#1 {main} [] []
[2016-11-04 12:19:57] production.ERROR: exception 'Database\QueryException' with message 'SQLSTATE[42S22]: Column not found: 1054 Unknown column 'nova_users.id' in 'having clause' (SQL: select `nova_users`.`username`, `nova_family_relation_joins`.`secondUserID`, `nova_family_relations`.`name_relation` from `nova_users` inner join `nova_family_tree_groups` on `nova_users`.`family_id` = `nova_family_tree_groups`.`treeID` inner join `nova_family_relation_joins` on `nova_users`.`family_id` = `nova_family_relation_joins`.`family_id` inner join `nova_family_relations` on `nova_family_relation_joins`.`relationID` = `nova_family_relations`.`id` where `nova_users`.`family_id` = 1 group by `nova_family_relation_joins`.`secondUserID` having `nova_users`.`id` = family_relation_joins.secondUserID)' in C:\xampp\htdocs\trust\system\Database\Connection.php:548
Stack trace:
#0 C:\xampp\htdocs\trust\system\Database\Connection.php(517): Database\Connection->runQueryCallback('select `nova_us...', Array, Object(Closure))
#1 C:\xampp\htdocs\trust\system\Database\Connection.php(268): Database\Connection->run('select `nova_us...', Array, Object(Closure))
#2 C:\xampp\htdocs\trust\system\Database\Query\Builder.php(1334): Database\Connection->select('select `nova_us...', Array)
#3 C:\xampp\htdocs\trust\system\Database\Query\Builder.php(1324): Database\Query\Builder->runSelect()
#4 C:\xampp\htdocs\trust\system\Database\Query\Builder.php(1311): Database\Query\Builder->getFresh(Array)
#5 C:\xampp\htdocs\trust\app\Controllers\Admin\Family.php(36): Database\Query\Builder->get()
#6 [internal function]: App\Controllers\Admin\Family->index()
#7 C:\xampp\htdocs\trust\system\Routing\Controller.php(240): call_user_func_array(Array, Array)
#8 C:\xampp\htdocs\trust\system\Routing\ControllerDispatcher.php(91): Routing\Controller->callAction('index', Array)
#9 C:\xampp\htdocs\trust\system\Routing\ControllerDispatcher.php(60): Routing\ControllerDispatcher->call(Object(App\Controllers\Admin\Family), Object(Routing\Route), 'index')
#10 C:\xampp\htdocs\trust\system\Routing\Router.php(958): Routing\ControllerDispatcher->dispatch(Object(Routing\Route), Object(Http\Request), 'App\\Controllers...', 'index')
#11 [internal function]: Routing\Router->Routing\{closure}()
#12 C:\xampp\htdocs\trust\system\Routing\Route.php(128): call_user_func_array(Object(Closure), Array)
#13 C:\xampp\htdocs\trust\system\Routing\Router.php(1026): Routing\Route->run()
#14 C:\xampp\htdocs\trust\system\Routing\Router.php(994): Routing\Router->dispatchToRoute(Object(Http\Request))
#15 C:\xampp\htdocs\trust\system\Foundation\Application.php(744): Routing\Router->dispatch(Object(Http\Request))
#16 C:\xampp\htdocs\trust\system\Foundation\Application.php(717): Foundation\Application->dispatch(Object(Http\Request))
#17 C:\xampp\htdocs\trust\shared\Http\ContentGuard.php(62): Foundation\Application->handle(Object(Http\Request), 1, true)
#18 C:\xampp\htdocs\trust\system\Session\Middleware.php(77): Shared\Http\ContentGuard->handle(Object(Http\Request), 1, true)
#19 C:\xampp\htdocs\trust\system\Cookie\Queue.php(49): Session\Middleware->handle(Object(Http\Request), 1, true)
#20 C:\xampp\htdocs\trust\system\Cookie\Guard.php(54): Cookie\Queue->handle(Object(Http\Request), 1, true)
#21 C:\xampp\htdocs\trust\vendor\stack\builder\src\Stack\StackedHttpKernel.php(23): Cookie\Guard->handle(Object(Http\Request), 1, true)
#22 C:\xampp\htdocs\trust\system\Foundation\Application.php(615): Stack\StackedHttpKernel->handle(Object(Http\Request))
#23 C:\xampp\htdocs\trust\app\Boot\Start.php(244): Foundation\Application->run()
#24 C:\xampp\htdocs\trust\public\index.php(37): require('C:\\xampp\\htdocs...')
#25 {main} [] []
[2016-11-04 12:24:32] production.ERROR: exception 'ErrorException' with message 'Undefined variable: secondName' in C:\xampp\htdocs\trust\app\Controllers\Admin\Family.php:46
Stack trace:
#0 C:\xampp\htdocs\trust\app\Controllers\Admin\Family.php(46): Exception\Handler->handleError(8, 'Undefined varia...', 'C:\\xampp\\htdocs...', 46, Array)
#1 [internal function]: App\Controllers\Admin\Family->index()
#2 C:\xampp\htdocs\trust\system\Routing\Controller.php(240): call_user_func_array(Array, Array)
#3 C:\xampp\htdocs\trust\system\Routing\ControllerDispatcher.php(91): Routing\Controller->callAction('index', Array)
#4 C:\xampp\htdocs\trust\system\Routing\ControllerDispatcher.php(60): Routing\ControllerDispatcher->call(Object(App\Controllers\Admin\Family), Object(Routing\Route), 'index')
#5 C:\xampp\htdocs\trust\system\Routing\Router.php(958): Routing\ControllerDispatcher->dispatch(Object(Routing\Route), Object(Http\Request), 'App\\Controllers...', 'index')
#6 [internal function]: Routing\Router->Routing\{closure}()
#7 C:\xampp\htdocs\trust\system\Routing\Route.php(128): call_user_func_array(Object(Closure), Array)
#8 C:\xampp\htdocs\trust\system\Routing\Router.php(1026): Routing\Route->run()
#9 C:\xampp\htdocs\trust\system\Routing\Router.php(994): Routing\Router->dispatchToRoute(Object(Http\Request))
#10 C:\xampp\htdocs\trust\system\Foundation\Application.php(744): Routing\Router->dispatch(Object(Http\Request))
#11 C:\xampp\htdocs\trust\system\Foundation\Application.php(717): Foundation\Application->dispatch(Object(Http\Request))
#12 C:\xampp\htdocs\trust\shared\Http\ContentGuard.php(62): Foundation\Application->handle(Object(Http\Request), 1, true)
#13 C:\xampp\htdocs\trust\system\Session\Middleware.php(77): Shared\Http\ContentGuard->handle(Object(Http\Request), 1, true)
#14 C:\xampp\htdocs\trust\system\Cookie\Queue.php(49): Session\Middleware->handle(Object(Http\Request), 1, true)
#15 C:\xampp\htdocs\trust\system\Cookie\Guard.php(54): Cookie\Queue->handle(Object(Http\Request), 1, true)
#16 C:\xampp\htdocs\trust\vendor\stack\builder\src\Stack\StackedHttpKernel.php(23): Cookie\Guard->handle(Object(Http\Request), 1, true)
#17 C:\xampp\htdocs\trust\system\Foundation\Application.php(615): Stack\StackedHttpKernel->handle(Object(Http\Request))
#18 C:\xampp\htdocs\trust\app\Boot\Start.php(244): Foundation\Application->run()
#19 C:\xampp\htdocs\trust\public\index.php(37): require('C:\\xampp\\htdocs...')
#20 {main} [] []
[2016-11-04 12:25:06] production.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Class 'App\Controllers\Admin\ArrayObject' not found' in C:\xampp\htdocs\trust\app\Controllers\Admin\Family.php:39
Stack trace:
#0 [internal function]: Exception\Handler->handleShutdown()
#1 {main} [] []
[2016-11-04 12:28:29] production.ERROR: exception 'ErrorException' with message 'Trying to get property of non-object' in C:\xampp\htdocs\trust\app\Controllers\Admin\Family.php:43
Stack trace:
#0 C:\xampp\htdocs\trust\app\Controllers\Admin\Family.php(43): Exception\Handler->handleError(8, 'Trying to get p...', 'C:\\xampp\\htdocs...', 43, Array)
#1 [internal function]: App\Controllers\Admin\Family->index()
#2 C:\xampp\htdocs\trust\system\Routing\Controller.php(240): call_user_func_array(Array, Array)
#3 C:\xampp\htdocs\trust\system\Routing\ControllerDispatcher.php(91): Routing\Controller->callAction('index', Array)
#4 C:\xampp\htdocs\trust\system\Routing\ControllerDispatcher.php(60): Routing\ControllerDispatcher->call(Object(App\Controllers\Admin\Family), Object(Routing\Route), 'index')
#5 C:\xampp\htdocs\trust\system\Routing\Router.php(958): Routing\ControllerDispatcher->dispatch(Object(Routing\Route), Object(Http\Request), 'App\\Controllers...', 'index')
#6 [internal function]: Routing\Router->Routing\{closure}()
#7 C:\xampp\htdocs\trust\system\Routing\Route.php(128): call_user_func_array(Object(Closure), Array)
#8 C:\xampp\htdocs\trust\system\Routing\Router.php(1026): Routing\Route->run()
#9 C:\xampp\htdocs\trust\system\Routing\Router.php(994): Routing\Router->dispatchToRoute(Object(Http\Request))
#10 C:\xampp\htdocs\trust\system\Foundation\Application.php(744): Routing\Router->dispatch(Object(Http\Request))
#11 C:\xampp\htdocs\trust\system\Foundation\Application.php(717): Foundation\Application->dispatch(Object(Http\Request))
#12 C:\xampp\htdocs\trust\shared\Http\ContentGuard.php(62): Foundation\Application->handle(Object(Http\Request), 1, true)
#13 C:\xampp\htdocs\trust\system\Session\Middleware.php(77): Shared\Http\ContentGuard->handle(Object(Http\Request), 1, true)
#14 C:\xampp\htdocs\trust\system\Cookie\Queue.php(49): Session\Middleware->handle(Object(Http\Request), 1, true)
#15 C:\xampp\htdocs\trust\system\Cookie\Guard.php(54): Cookie\Queue->handle(Object(Http\Request), 1, true)
#16 C:\xampp\htdocs\trust\vendor\stack\builder\src\Stack\StackedHttpKernel.php(23): Cookie\Guard->handle(Object(Http\Request), 1, true)
#17 C:\xampp\htdocs\trust\system\Foundation\Application.php(615): Stack\StackedHttpKernel->handle(Object(Http\Request))
#18 C:\xampp\htdocs\trust\app\Boot\Start.php(244): Foundation\Application->run()
#19 C:\xampp\htdocs\trust\public\index.php(37): require('C:\\xampp\\htdocs...')
#20 {main} [] []
[2016-11-04 12:30:24] production.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected 'pr' (T_STRING)' in C:\xampp\htdocs\trust\app\Controllers\Admin\Family.php:43
Stack trace:
#0 [internal function]: Exception\Handler->handleShutdown()
#1 {main} [] []
[2016-11-04 12:30:41] production.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected ';'' in C:\xampp\htdocs\trust\app\Controllers\Admin\Family.php:42
Stack trace:
#0 [internal function]: Exception\Handler->handleShutdown()
#1 {main} [] []
[2016-11-04 12:30:51] production.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Class 'App\Controllers\Admin\ArrayObject' not found' in C:\xampp\htdocs\trust\app\Controllers\Admin\Family.php:37
Stack trace:
#0 [internal function]: Exception\Handler->handleShutdown()
#1 {main} [] []
[2016-11-04 12:31:19] production.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Class 'App\Controllers\Admin\ArrayObject' not found' in C:\xampp\htdocs\trust\app\Controllers\Admin\Family.php:37
Stack trace:
#0 [internal function]: Exception\Handler->handleShutdown()
#1 {main} [] []
[2016-11-04 12:31:36] production.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Class 'App\Controllers\Admin\ArrayObject' not found' in C:\xampp\htdocs\trust\app\Controllers\Admin\Family.php:37
Stack trace:
#0 [internal function]: Exception\Handler->handleShutdown()
#1 {main} [] []
[2016-11-04 12:37:13] production.ERROR: exception 'Database\QueryException' with message 'SQLSTATE[42S22]: Column not found: 1054 Unknown column 'nova_c.username' in 'on clause' (SQL: select * from `nova_users` inner join `nova_family_tree_groups` on `nova_users`.`family_id` = `nova_family_tree_groups`.`treeID` inner join `nova_family_relation_joins` on `nova_users`.`family_id` = `nova_family_relation_joins`.`family_id` inner join `nova_family_relations` on `nova_family_relation_joins`.`relationID` = `nova_family_relations`.`id` left join `nova_users` as `c` on `nova_c`.`username` = `nova_family_relation_joins`.`secondUserID` where `nova_users`.`family_id` = 1 group by `nova_family_relation_joins`.`secondUserID`)' in C:\xampp\htdocs\trust\system\Database\Connection.php:548
Stack trace:
#0 C:\xampp\htdocs\trust\system\Database\Connection.php(517): Database\Connection->runQueryCallback('select * from `...', Array, Object(Closure))
#1 C:\xampp\htdocs\trust\system\Database\Connection.php(268): Database\Connection->run('select * from `...', Array, Object(Closure))
#2 C:\xampp\htdocs\trust\system\Database\Query\Builder.php(1334): Database\Connection->select('select * from `...', Array)
#3 C:\xampp\htdocs\trust\system\Database\Query\Builder.php(1324): Database\Query\Builder->runSelect()
#4 C:\xampp\htdocs\trust\system\Database\Query\Builder.php(1311): Database\Query\Builder->getFresh(Array)
#5 C:\xampp\htdocs\trust\app\Controllers\Admin\Family.php(36): Database\Query\Builder->get()
#6 [internal function]: App\Controllers\Admin\Family->index()
#7 C:\xampp\htdocs\trust\system\Routing\Controller.php(240): call_user_func_array(Array, Array)
#8 C:\xampp\htdocs\trust\system\Routing\ControllerDispatcher.php(91): Routing\Controller->callAction('index', Array)
#9 C:\xampp\htdocs\trust\system\Routing\ControllerDispatcher.php(60): Routing\ControllerDispatcher->call(Object(App\Controllers\Admin\Family), Object(Routing\Route), 'index')
#10 C:\xampp\htdocs\trust\system\Routing\Router.php(958): Routing\ControllerDispatcher->dispatch(Object(Routing\Route), Object(Http\Request), 'App\\Controllers...', 'index')
#11 [internal function]: Routing\Router->Routing\{closure}()
#12 C:\xampp\htdocs\trust\system\Routing\Route.php(128): call_user_func_array(Object(Closure), Array)
#13 C:\xampp\htdocs\trust\system\Routing\Router.php(1026): Routing\Route->run()
#14 C:\xampp\htdocs\trust\system\Routing\Router.php(994): Routing\Router->dispatchToRoute(Object(Http\Request))
#15 C:\xampp\htdocs\trust\system\Foundation\Application.php(744): Routing\Router->dispatch(Object(Http\Request))
#16 C:\xampp\htdocs\trust\system\Foundation\Application.php(717): Foundation\Application->dispatch(Object(Http\Request))
#17 C:\xampp\htdocs\trust\shared\Http\ContentGuard.php(62): Foundation\Application->handle(Object(Http\Request), 1, true)
#18 C:\xampp\htdocs\trust\system\Session\Middleware.php(77): Shared\Http\ContentGuard->handle(Object(Http\Request), 1, true)
#19 C:\xampp\htdocs\trust\system\Cookie\Queue.php(49): Session\Middleware->handle(Object(Http\Request), 1, true)
#20 C:\xampp\htdocs\trust\system\Cookie\Guard.php(54): Cookie\Queue->handle(Object(Http\Request), 1, true)
#21 C:\xampp\htdocs\trust\vendor\stack\builder\src\Stack\StackedHttpKernel.php(23): Cookie\Guard->handle(Object(Http\Request), 1, true)
#22 C:\xampp\htdocs\trust\system\Foundation\Application.php(615): Stack\StackedHttpKernel->handle(Object(Http\Request))
#23 C:\xampp\htdocs\trust\app\Boot\Start.php(244): Foundation\Application->run()
#24 C:\xampp\htdocs\trust\public\index.php(37): require('C:\\xampp\\htdocs...')
#25 {main} [] []
[2016-11-04 12:37:30] production.ERROR: exception 'Database\QueryException' with message 'SQLSTATE[42S22]: Column not found: 1054 Unknown column 'nova_c.username' in 'on clause' (SQL: select `nova_users`.`username`, `nova_family_relation_joins`.`secondUserID`, `nova_family_relations`.`name_relation` from `nova_users` inner join `nova_family_tree_groups` on `nova_users`.`family_id` = `nova_family_tree_groups`.`treeID` inner join `nova_family_relation_joins` on `nova_users`.`family_id` = `nova_family_relation_joins`.`family_id` inner join `nova_family_relations` on `nova_family_relation_joins`.`relationID` = `nova_family_relations`.`id` left join `nova_users` as `c` on `nova_c`.`username` = `nova_family_relation_joins`.`secondUserID` where `nova_users`.`family_id` = 1 group by `nova_family_relation_joins`.`secondUserID`)' in C:\xampp\htdocs\trust\system\Database\Connection.php:548
Stack trace:
#0 C:\xampp\htdocs\trust\system\Database\Connection.php(517): Database\Connection->runQueryCallback('select `nova_us...', Array, Object(Closure))
#1 C:\xampp\htdocs\trust\system\Database\Connection.php(268): Database\Connection->run('select `nova_us...', Array, Object(Closure))
#2 C:\xampp\htdocs\trust\system\Database\Query\Builder.php(1334): Database\Connection->select('select `nova_us...', Array)
#3 C:\xampp\htdocs\trust\system\Database\Query\Builder.php(1324): Database\Query\Builder->runSelect()
#4 C:\xampp\htdocs\trust\system\Database\Query\Builder.php(1311): Database\Query\Builder->getFresh(Array)
#5 C:\xampp\htdocs\trust\app\Controllers\Admin\Family.php(36): Database\Query\Builder->get()
#6 [internal function]: App\Controllers\Admin\Family->index()
#7 C:\xampp\htdocs\trust\system\Routing\Controller.php(240): call_user_func_array(Array, Array)
#8 C:\xampp\htdocs\trust\system\Routing\ControllerDispatcher.php(91): Routing\Controller->callAction('index', Array)
#9 C:\xampp\htdocs\trust\system\Routing\ControllerDispatcher.php(60): Routing\ControllerDispatcher->call(Object(App\Controllers\Admin\Family), Object(Routing\Route), 'index')
#10 C:\xampp\htdocs\trust\system\Routing\Router.php(958): Routing\ControllerDispatcher->dispatch(Object(Routing\Route), Object(Http\Request), 'App\\Controllers...', 'index')
#11 [internal function]: Routing\Router->Routing\{closure}()
#12 C:\xampp\htdocs\trust\system\Routing\Route.php(128): call_user_func_array(Object(Closure), Array)
#13 C:\xampp\htdocs\trust\system\Routing\Router.php(1026): Routing\Route->run()
#14 C:\xampp\htdocs\trust\system\Routing\Router.php(994): Routing\Router->dispatchToRoute(Object(Http\Request))
#15 C:\xampp\htdocs\trust\system\Foundation\Application.php(744): Routing\Router->dispatch(Object(Http\Request))
#16 C:\xampp\htdocs\trust\system\Foundation\Application.php(717): Foundation\Application->dispatch(Object(Http\Request))
#17 C:\xampp\htdocs\trust\shared\Http\ContentGuard.php(62): Foundation\Application->handle(Object(Http\Request), 1, true)
#18 C:\xampp\htdocs\trust\system\Session\Middleware.php(77): Shared\Http\ContentGuard->handle(Object(Http\Request), 1, true)
#19 C:\xampp\htdocs\trust\system\Cookie\Queue.php(49): Session\Middleware->handle(Object(Http\Request), 1, true)
#20 C:\xampp\htdocs\trust\system\Cookie\Guard.php(54): Cookie\Queue->handle(Object(Http\Request), 1, true)
#21 C:\xampp\htdocs\trust\vendor\stack\builder\src\Stack\StackedHttpKernel.php(23): Cookie\Guard->handle(Object(Http\Request), 1, true)
#22 C:\xampp\htdocs\trust\system\Foundation\Application.php(615): Stack\StackedHttpKernel->handle(Object(Http\Request))
#23 C:\xampp\htdocs\trust\app\Boot\Start.php(244): Foundation\Application->run()
#24 C:\xampp\htdocs\trust\public\index.php(37): require('C:\\xampp\\htdocs...')
#25 {main} [] []
[2016-11-04 12:37:44] production.ERROR: exception 'Database\QueryException' with message 'SQLSTATE[42000]: Syntax error or access violation: 1066 Not unique table/alias: 'nova_users' (SQL: select `nova_users`.`username`, `nova_family_relation_joins`.`secondUserID`, `nova_family_relations`.`name_relation` from `nova_users` inner join `nova_family_tree_groups` on `nova_users`.`family_id` = `nova_family_tree_groups`.`treeID` inner join `nova_family_relation_joins` on `nova_users`.`family_id` = `nova_family_relation_joins`.`family_id` inner join `nova_family_relations` on `nova_family_relation_joins`.`relationID` = `nova_family_relations`.`id` left join `nova_users` on `nova_users`.`username` = `nova_family_relation_joins`.`secondUserID` where `nova_users`.`family_id` = 1 group by `nova_family_relation_joins`.`secondUserID`)' in C:\xampp\htdocs\trust\system\Database\Connection.php:548
Stack trace:
#0 C:\xampp\htdocs\trust\system\Database\Connection.php(517): Database\Connection->runQueryCallback('select `nova_us...', Array, Object(Closure))
#1 C:\xampp\htdocs\trust\system\Database\Connection.php(268): Database\Connection->run('select `nova_us...', Array, Object(Closure))
#2 C:\xampp\htdocs\trust\system\Database\Query\Builder.php(1334): Database\Connection->select('select `nova_us...', Array)
#3 C:\xampp\htdocs\trust\system\Database\Query\Builder.php(1324): Database\Query\Builder->runSelect()
#4 C:\xampp\htdocs\trust\system\Database\Query\Builder.php(1311): Database\Query\Builder->getFresh(Array)
#5 C:\xampp\htdocs\trust\app\Controllers\Admin\Family.php(36): Database\Query\Builder->get()
#6 [internal function]: App\Controllers\Admin\Family->index()
#7 C:\xampp\htdocs\trust\system\Routing\Controller.php(240): call_user_func_array(Array, Array)
#8 C:\xampp\htdocs\trust\system\Routing\ControllerDispatcher.php(91): Routing\Controller->callAction('index', Array)
#9 C:\xampp\htdocs\trust\system\Routing\ControllerDispatcher.php(60): Routing\ControllerDispatcher->call(Object(App\Controllers\Admin\Family), Object(Routing\Route), 'index')
#10 C:\xampp\htdocs\trust\system\Routing\Router.php(958): Routing\ControllerDispatcher->dispatch(Object(Routing\Route), Object(Http\Request), 'App\\Controllers...', 'index')
#11 [internal function]: Routing\Router->Routing\{closure}()
#12 C:\xampp\htdocs\trust\system\Routing\Route.php(128): call_user_func_array(Object(Closure), Array)
#13 C:\xampp\htdocs\trust\system\Routing\Router.php(1026): Routing\Route->run()
#14 C:\xampp\htdocs\trust\system\Routing\Router.php(994): Routing\Router->dispatchToRoute(Object(Http\Request))
#15 C:\xampp\htdocs\trust\system\Foundation\Application.php(744): Routing\Router->dispatch(Object(Http\Request))
#16 C:\xampp\htdocs\trust\system\Foundation\Application.php(717): Foundation\Application->dispatch(Object(Http\Request))
#17 C:\xampp\htdocs\trust\shared\Http\ContentGuard.php(62): Foundation\Application->handle(Object(Http\Request), 1, true)
#18 C:\xampp\htdocs\trust\system\Session\Middleware.php(77): Shared\Http\ContentGuard->handle(Object(Http\Request), 1, true)
#19 C:\xampp\htdocs\trust\system\Cookie\Queue.php(49): Session\Middleware->handle(Object(Http\Request), 1, true)
#20 C:\xampp\htdocs\trust\system\Cookie\Guard.php(54): Cookie\Queue->handle(Object(Http\Request), 1, true)
#21 C:\xampp\htdocs\trust\vendor\stack\builder\src\Stack\StackedHttpKernel.php(23): Cookie\Guard->handle(Object(Http\Request), 1, true)
#22 C:\xampp\htdocs\trust\system\Foundation\Application.php(615): Stack\StackedHttpKernel->handle(Object(Http\Request))
#23 C:\xampp\htdocs\trust\app\Boot\Start.php(244): Foundation\Application->run()
#24 C:\xampp\htdocs\trust\public\index.php(37): require('C:\\xampp\\htdocs...')
#25 {main} [] []
[2016-11-04 12:41:23] production.ERROR: exception 'ErrorException' with message 'Undefined variable: secondName' in C:\xampp\htdocs\trust\app\Controllers\Admin\Family.php:54
Stack trace:
#0 C:\xampp\htdocs\trust\app\Controllers\Admin\Family.php(54): Exception\Handler->handleError(8, 'Undefined varia...', 'C:\\xampp\\htdocs...', 54, Array)
#1 [internal function]: App\Controllers\Admin\Family->index()
#2 C:\xampp\htdocs\trust\system\Routing\Controller.php(240): call_user_func_array(Array, Array)
#3 C:\xampp\htdocs\trust\system\Routing\ControllerDispatcher.php(91): Routing\Controller->callAction('index', Array)
#4 C:\xampp\htdocs\trust\system\Routing\ControllerDispatcher.php(60): Routing\ControllerDispatcher->call(Object(App\Controllers\Admin\Family), Object(Routing\Route), 'index')
#5 C:\xampp\htdocs\trust\system\Routing\Router.php(958): Routing\ControllerDispatcher->dispatch(Object(Routing\Route), Object(Http\Request), 'App\\Controllers...', 'index')
#6 [internal function]: Routing\Router->Routing\{closure}()
#7 C:\xampp\htdocs\trust\system\Routing\Route.php(128): call_user_func_array(Object(Closure), Array)
#8 C:\xampp\htdocs\trust\system\Routing\Router.php(1026): Routing\Route->run()
#9 C:\xampp\htdocs\trust\system\Routing\Router.php(994): Routing\Router->dispatchToRoute(Object(Http\Request))
#10 C:\xampp\htdocs\trust\system\Foundation\Application.php(744): Routing\Router->dispatch(Object(Http\Request))
#11 C:\xampp\htdocs\trust\system\Foundation\Application.php(717): Foundation\Application->dispatch(Object(Http\Request))
#12 C:\xampp\htdocs\trust\shared\Http\ContentGuard.php(62): Foundation\Application->handle(Object(Http\Request), 1, true)
#13 C:\xampp\htdocs\trust\system\Session\Middleware.php(77): Shared\Http\ContentGuard->handle(Object(Http\Request), 1, true)
#14 C:\xampp\htdocs\trust\system\Cookie\Queue.php(49): Session\Middleware->handle(Object(Http\Request), 1, true)
#15 C:\xampp\htdocs\trust\system\Cookie\Guard.php(54): Cookie\Queue->handle(Object(Http\Request), 1, true)
#16 C:\xampp\htdocs\trust\vendor\stack\builder\src\Stack\StackedHttpKernel.php(23): Cookie\Guard->handle(Object(Http\Request), 1, true)
#17 C:\xampp\htdocs\trust\system\Foundation\Application.php(615): Stack\StackedHttpKernel->handle(Object(Http\Request))
#18 C:\xampp\htdocs\trust\app\Boot\Start.php(244): Foundation\Application->run()
#19 C:\xampp\htdocs\trust\public\index.php(37): require('C:\\xampp\\htdocs...')
#20 {main} [] []
[2016-11-04 12:41:37] production.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected '$name' (T_VARIABLE), expecting ',' or ';'' in C:\xampp\htdocs\trust\app\Views\Admin\Family\index.php:3
Stack trace:
#0 [internal function]: Exception\Handler->handleShutdown()
#1 {main} [] []
[2016-11-04 12:42:23] production.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected '$temp' (T_VARIABLE), expecting ',' or ';'' in C:\xampp\htdocs\trust\app\Views\Admin\Family\index.php:3
Stack trace:
#0 [internal function]: Exception\Handler->handleShutdown()
#1 {main} [] []
[2016-11-04 12:42:42] production.ERROR: exception 'ErrorException' with message 'The use statement with non-compound name 'DB' has no effect' in C:\xampp\htdocs\trust\app\Views\Admin\Family\index.php:2
Stack trace:
#0 C:\xampp\htdocs\trust\system\View\Engines\PhpEngine.php(56): Exception\Handler->handleError(2, 'The use stateme...', 'C:\\xampp\\htdocs...', 2, Array)
#1 C:\xampp\htdocs\trust\system\View\Engines\PhpEngine.php(56): View\Engines\PhpEngine::evaluatePath()
#2 C:\xampp\htdocs\trust\system\View\Engines\PhpEngine.php(31): View\Engines\PhpEngine->evaluatePath('C:\\xampp\\htdocs...', Array)
#3 C:\xampp\htdocs\trust\system\View\View.php(96): View\Engines\PhpEngine->get('C:\\xampp\\htdocs...', Array)
#4 C:\xampp\htdocs\trust\system\View\View.php(82): View\View->renderContents()
#5 C:\xampp\htdocs\trust\system\View\View.php(111): View\View->render()
#6 C:\xampp\htdocs\trust\system\View\View.php(96): View\View->gatherData()
#7 C:\xampp\htdocs\trust\system\View\View.php(82): View\View->renderContents()
#8 C:\xampp\htdocs\trust\app\Core\Controller.php(70): View\View->render()
#9 C:\xampp\htdocs\trust\system\Routing\Controller.php(250): App\Core\Controller->processResponse(Object(View\View))
#10 C:\xampp\htdocs\trust\system\Routing\ControllerDispatcher.php(91): Routing\Controller->callAction('index', Array)
#11 C:\xampp\htdocs\trust\system\Routing\ControllerDispatcher.php(60): Routing\ControllerDispatcher->call(Object(App\Controllers\Admin\Family), Object(Routing\Route), 'index')
#12 C:\xampp\htdocs\trust\system\Routing\Router.php(958): Routing\ControllerDispatcher->dispatch(Object(Routing\Route), Object(Http\Request), 'App\\Controllers...', 'index')
#13 [internal function]: Routing\Router->Routing\{closure}()
#14 C:\xampp\htdocs\trust\system\Routing\Route.php(128): call_user_func_array(Object(Closure), Array)
#15 C:\xampp\htdocs\trust\system\Routing\Router.php(1026): Routing\Route->run()
#16 C:\xampp\htdocs\trust\system\Routing\Router.php(994): Routing\Router->dispatchToRoute(Object(Http\Request))
#17 C:\xampp\htdocs\trust\system\Foundation\Application.php(744): Routing\Router->dispatch(Object(Http\Request))
#18 C:\xampp\htdocs\trust\system\Foundation\Application.php(717): Foundation\Application->dispatch(Object(Http\Request))
#19 C:\xampp\htdocs\trust\shared\Http\ContentGuard.php(62): Foundation\Application->handle(Object(Http\Request), 1, true)
#20 C:\xampp\htdocs\trust\system\Session\Middleware.php(77): Shared\Http\ContentGuard->handle(Object(Http\Request), 1, true)
#21 C:\xampp\htdocs\trust\system\Cookie\Queue.php(49): Session\Middleware->handle(Object(Http\Request), 1, true)
#22 C:\xampp\htdocs\trust\system\Cookie\Guard.php(54): Cookie\Queue->handle(Object(Http\Request), 1, true)
#23 C:\xampp\htdocs\trust\vendor\stack\builder\src\Stack\StackedHttpKernel.php(23): Cookie\Guard->handle(Object(Http\Request), 1, true)
#24 C:\xampp\htdocs\trust\system\Foundation\Application.php(615): Stack\StackedHttpKernel->handle(Object(Http\Request))
#25 C:\xampp\htdocs\trust\app\Boot\Start.php(244): Foundation\Application->run()
#26 C:\xampp\htdocs\trust\public\index.php(37): require('C:\\xampp\\htdocs...')
#27 {main} [] []
[2016-11-04 12:51:02] production.ERROR: exception 'ErrorException' with message 'Undefined variable: name' in C:\xampp\htdocs\trust\app\Views\Admin\Family\index.php:50
Stack trace:
#0 C:\xampp\htdocs\trust\app\Views\Admin\Family\index.php(50): Exception\Handler->handleError(8, 'Undefined varia...', 'C:\\xampp\\htdocs...', 50, Array)
#1 C:\xampp\htdocs\trust\system\View\Engines\PhpEngine.php(56): include('C:\\xampp\\htdocs...')
#2 C:\xampp\htdocs\trust\system\View\Engines\PhpEngine.php(31): View\Engines\PhpEngine->evaluatePath('C:\\xampp\\htdocs...', Array)
#3 C:\xampp\htdocs\trust\system\View\View.php(96): View\Engines\PhpEngine->get('C:\\xampp\\htdocs...', Array)
#4 C:\xampp\htdocs\trust\system\View\View.php(82): View\View->renderContents()
#5 C:\xampp\htdocs\trust\system\View\View.php(111): View\View->render()
#6 C:\xampp\htdocs\trust\system\View\View.php(96): View\View->gatherData()
#7 C:\xampp\htdocs\trust\system\View\View.php(82): View\View->renderContents()
#8 C:\xampp\htdocs\trust\app\Core\Controller.php(70): View\View->render()
#9 C:\xampp\htdocs\trust\system\Routing\Controller.php(250): App\Core\Controller->processResponse(Object(View\View))
#10 C:\xampp\htdocs\trust\system\Routing\ControllerDispatcher.php(91): Routing\Controller->callAction('index', Array)
#11 C:\xampp\htdocs\trust\system\Routing\ControllerDispatcher.php(60): Routing\ControllerDispatcher->call(Object(App\Controllers\Admin\Family), Object(Routing\Route), 'index')
#12 C:\xampp\htdocs\trust\system\Routing\Router.php(958): Routing\ControllerDispatcher->dispatch(Object(Routing\Route), Object(Http\Request), 'App\\Controllers...', 'index')
#13 [internal function]: Routing\Router->Routing\{closure}()
#14 C:\xampp\htdocs\trust\system\Routing\Route.php(128): call_user_func_array(Object(Closure), Array)
#15 C:\xampp\htdocs\trust\system\Routing\Router.php(1026): Routing\Route->run()
#16 C:\xampp\htdocs\trust\system\Routing\Router.php(994): Routing\Router->dispatchToRoute(Object(Http\Request))
#17 C:\xampp\htdocs\trust\system\Foundation\Application.php(744): Routing\Router->dispatch(Object(Http\Request))
#18 C:\xampp\htdocs\trust\system\Foundation\Application.php(717): Foundation\Application->dispatch(Object(Http\Request))
#19 C:\xampp\htdocs\trust\shared\Http\ContentGuard.php(62): Foundation\Application->handle(Object(Http\Request), 1, true)
#20 C:\xampp\htdocs\trust\system\Session\Middleware.php(77): Shared\Http\ContentGuard->handle(Object(Http\Request), 1, true)
#21 C:\xampp\htdocs\trust\system\Cookie\Queue.php(49): Session\Middleware->handle(Object(Http\Request), 1, true)
#22 C:\xampp\htdocs\trust\system\Cookie\Guard.php(54): Cookie\Queue->handle(Object(Http\Request), 1, true)
#23 C:\xampp\htdocs\trust\vendor\stack\builder\src\Stack\StackedHttpKernel.php(23): Cookie\Guard->handle(Object(Http\Request), 1, true)
#24 C:\xampp\htdocs\trust\system\Foundation\Application.php(615): Stack\StackedHttpKernel->handle(Object(Http\Request))
#25 C:\xampp\htdocs\trust\app\Boot\Start.php(244): Foundation\Application->run()
#26 C:\xampp\htdocs\trust\public\index.php(37): require('C:\\xampp\\htdocs...')
#27 {main} [] []
[2016-11-04 12:52:32] production.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected ')', expecting ',' or ';'' in C:\xampp\htdocs\trust\app\Views\Admin\Family\index.php:39
Stack trace:
#0 [internal function]: Exception\Handler->handleShutdown()
#1 {main} [] []
[2016-11-04 12:52:40] production.ERROR: exception 'ErrorException' with message 'Undefined offset: 1' in C:\xampp\htdocs\trust\app\Views\Admin\Family\index.php:39
Stack trace:
#0 C:\xampp\htdocs\trust\app\Views\Admin\Family\index.php(39): Exception\Handler->handleError(8, 'Undefined offse...', 'C:\\xampp\\htdocs...', 39, Array)
#1 C:\xampp\htdocs\trust\system\View\Engines\PhpEngine.php(56): include('C:\\xampp\\htdocs...')
#2 C:\xampp\htdocs\trust\system\View\Engines\PhpEngine.php(31): View\Engines\PhpEngine->evaluatePath('C:\\xampp\\htdocs...', Array)
#3 C:\xampp\htdocs\trust\system\View\View.php(96): View\Engines\PhpEngine->get('C:\\xampp\\htdocs...', Array)
#4 C:\xampp\htdocs\trust\system\View\View.php(82): View\View->renderContents()
#5 C:\xampp\htdocs\trust\system\View\View.php(111): View\View->render()
#6 C:\xampp\htdocs\trust\system\View\View.php(96): View\View->gatherData()
#7 C:\xampp\htdocs\trust\system\View\View.php(82): View\View->renderContents()
#8 C:\xampp\htdocs\trust\app\Core\Controller.php(70): View\View->render()
#9 C:\xampp\htdocs\trust\system\Routing\Controller.php(250): App\Core\Controller->processResponse(Object(View\View))
#10 C:\xampp\htdocs\trust\system\Routing\ControllerDispatcher.php(91): Routing\Controller->callAction('index', Array)
#11 C:\xampp\htdocs\trust\system\Routing\ControllerDispatcher.php(60): Routing\ControllerDispatcher->call(Object(App\Controllers\Admin\Family), Object(Routing\Route), 'index')
#12 C:\xampp\htdocs\trust\system\Routing\Router.php(958): Routing\ControllerDispatcher->dispatch(Object(Routing\Route), Object(Http\Request), 'App\\Controllers...', 'index')
#13 [internal function]: Routing\Router->Routing\{closure}()
#14 C:\xampp\htdocs\trust\system\Routing\Route.php(128): call_user_func_array(Object(Closure), Array)
#15 C:\xampp\htdocs\trust\system\Routing\Router.php(1026): Routing\Route->run()
#16 C:\xampp\htdocs\trust\system\Routing\Router.php(994): Routing\Router->dispatchToRoute(Object(Http\Request))
#17 C:\xampp\htdocs\trust\system\Foundation\Application.php(744): Routing\Router->dispatch(Object(Http\Request))
#18 C:\xampp\htdocs\trust\system\Foundation\Application.php(717): Foundation\Application->dispatch(Object(Http\Request))
#19 C:\xampp\htdocs\trust\shared\Http\ContentGuard.php(62): Foundation\Application->handle(Object(Http\Request), 1, true)
#20 C:\xampp\htdocs\trust\system\Session\Middleware.php(77): Shared\Http\ContentGuard->handle(Object(Http\Request), 1, true)
#21 C:\xampp\htdocs\trust\system\Cookie\Queue.php(49): Session\Middleware->handle(Object(Http\Request), 1, true)
#22 C:\xampp\htdocs\trust\system\Cookie\Guard.php(54): Cookie\Queue->handle(Object(Http\Request), 1, true)
#23 C:\xampp\htdocs\trust\vendor\stack\builder\src\Stack\StackedHttpKernel.php(23): Cookie\Guard->handle(Object(Http\Request), 1, true)
#24 C:\xampp\htdocs\trust\system\Foundation\Application.php(615): Stack\StackedHttpKernel->handle(Object(Http\Request))
#25 C:\xampp\htdocs\trust\app\Boot\Start.php(244): Foundation\Application->run()
#26 C:\xampp\htdocs\trust\public\index.php(37): require('C:\\xampp\\htdocs...')
#27 {main} [] []
[2016-11-04 12:57:10] production.ERROR: exception 'ErrorException' with message 'Only variables should be passed by reference' in C:\xampp\htdocs\trust\app\Views\Admin\Family\index.php:8
Stack trace:
#0 C:\xampp\htdocs\trust\app\Views\Admin\Family\index.php(8): Exception\Handler->handleError(2048, 'Only variables ...', 'C:\\xampp\\htdocs...', 8, Array)
#1 C:\xampp\htdocs\trust\system\View\Engines\PhpEngine.php(56): include('C:\\xampp\\htdocs...')
#2 C:\xampp\htdocs\trust\system\View\Engines\PhpEngine.php(31): View\Engines\PhpEngine->evaluatePath('C:\\xampp\\htdocs...', Array)
#3 C:\xampp\htdocs\trust\system\View\View.php(96): View\Engines\PhpEngine->get('C:\\xampp\\htdocs...', Array)
#4 C:\xampp\htdocs\trust\system\View\View.php(82): View\View->renderContents()
#5 C:\xampp\htdocs\trust\system\View\View.php(111): View\View->render()
#6 C:\xampp\htdocs\trust\system\View\View.php(96): View\View->gatherData()
#7 C:\xampp\htdocs\trust\system\View\View.php(82): View\View->renderContents()
#8 C:\xampp\htdocs\trust\app\Core\Controller.php(70): View\View->render()
#9 C:\xampp\htdocs\trust\system\Routing\Controller.php(250): App\Core\Controller->processResponse(Object(View\View))
#10 C:\xampp\htdocs\trust\system\Routing\ControllerDispatcher.php(91): Routing\Controller->callAction('index', Array)
#11 C:\xampp\htdocs\trust\system\Routing\ControllerDispatcher.php(60): Routing\ControllerDispatcher->call(Object(App\Controllers\Admin\Family), Object(Routing\Route), 'index')
#12 C:\xampp\htdocs\trust\system\Routing\Router.php(958): Routing\ControllerDispatcher->dispatch(Object(Routing\Route), Object(Http\Request), 'App\\Controllers...', 'index')
#13 [internal function]: Routing\Router->Routing\{closure}()
#14 C:\xampp\htdocs\trust\system\Routing\Route.php(128): call_user_func_array(Object(Closure), Array)
#15 C:\xampp\htdocs\trust\system\Routing\Router.php(1026): Routing\Route->run()
#16 C:\xampp\htdocs\trust\system\Routing\Router.php(994): Routing\Router->dispatchToRoute(Object(Http\Request))
#17 C:\xampp\htdocs\trust\system\Foundation\Application.php(744): Routing\Router->dispatch(Object(Http\Request))
#18 C:\xampp\htdocs\trust\system\Foundation\Application.php(717): Foundation\Application->dispatch(Object(Http\Request))
#19 C:\xampp\htdocs\trust\shared\Http\ContentGuard.php(62): Foundation\Application->handle(Object(Http\Request), 1, true)
#20 C:\xampp\htdocs\trust\system\Session\Middleware.php(77): Shared\Http\ContentGuard->handle(Object(Http\Request), 1, true)
#21 C:\xampp\htdocs\trust\system\Cookie\Queue.php(49): Session\Middleware->handle(Object(Http\Request), 1, true)
#22 C:\xampp\htdocs\trust\system\Cookie\Guard.php(54): Cookie\Queue->handle(Object(Http\Request), 1, true)
#23 C:\xampp\htdocs\trust\vendor\stack\builder\src\Stack\StackedHttpKernel.php(23): Cookie\Guard->handle(Object(Http\Request), 1, true)
#24 C:\xampp\htdocs\trust\system\Foundation\Application.php(615): Stack\StackedHttpKernel->handle(Object(Http\Request))
#25 C:\xampp\htdocs\trust\app\Boot\Start.php(244): Foundation\Application->run()
#26 C:\xampp\htdocs\trust\public\index.php(37): require('C:\\xampp\\htdocs...')
#27 {main} [] []
[2016-11-04 12:58:27] production.ERROR: exception 'ErrorException' with message 'Undefined offset: 1' in C:\xampp\htdocs\trust\app\Views\Admin\Family\index.php:9
Stack trace:
#0 C:\xampp\htdocs\trust\app\Views\Admin\Family\index.php(9): Exception\Handler->handleError(8, 'Undefined offse...', 'C:\\xampp\\htdocs...', 9, Array)
#1 C:\xampp\htdocs\trust\system\View\Engines\PhpEngine.php(56): include('C:\\xampp\\htdocs...')
#2 C:\xampp\htdocs\trust\system\View\Engines\PhpEngine.php(31): View\Engines\PhpEngine->evaluatePath('C:\\xampp\\htdocs...', Array)
#3 C:\xampp\htdocs\trust\system\View\View.php(96): View\Engines\PhpEngine->get('C:\\xampp\\htdocs...', Array)
#4 C:\xampp\htdocs\trust\system\View\View.php(82): View\View->renderContents()
#5 C:\xampp\htdocs\trust\system\View\View.php(111): View\View->render()
#6 C:\xampp\htdocs\trust\system\View\View.php(96): View\View->gatherData()
#7 C:\xampp\htdocs\trust\system\View\View.php(82): View\View->renderContents()
#8 C:\xampp\htdocs\trust\app\Core\Controller.php(70): View\View->render()
#9 C:\xampp\htdocs\trust\system\Routing\Controller.php(250): App\Core\Controller->processResponse(Object(View\View))
#10 C:\xampp\htdocs\trust\system\Routing\ControllerDispatcher.php(91): Routing\Controller->callAction('index', Array)
#11 C:\xampp\htdocs\trust\system\Routing\ControllerDispatcher.php(60): Routing\ControllerDispatcher->call(Object(App\Controllers\Admin\Family), Object(Routing\Route), 'index')
#12 C:\xampp\htdocs\trust\system\Routing\Router.php(958): Routing\ControllerDispatcher->dispatch(Object(Routing\Route), Object(Http\Request), 'App\\Controllers...', 'index')
#13 [internal function]: Routing\Router->Routing\{closure}()
#14 C:\xampp\htdocs\trust\system\Routing\Route.php(128): call_user_func_array(Object(Closure), Array)
#15 C:\xampp\htdocs\trust\system\Routing\Router.php(1026): Routing\Route->run()
#16 C:\xampp\htdocs\trust\system\Routing\Router.php(994): Routing\Router->dispatchToRoute(Object(Http\Request))
#17 C:\xampp\htdocs\trust\system\Foundation\Application.php(744): Routing\Router->dispatch(Object(Http\Request))
#18 C:\xampp\htdocs\trust\system\Foundation\Application.php(717): Foundation\Application->dispatch(Object(Http\Request))
#19 C:\xampp\htdocs\trust\shared\Http\ContentGuard.php(62): Foundation\Application->handle(Object(Http\Request), 1, true)
#20 C:\xampp\htdocs\trust\system\Session\Middleware.php(77): Shared\Http\ContentGuard->handle(Object(Http\Request), 1, true)
#21 C:\xampp\htdocs\trust\system\Cookie\Queue.php(49): Session\Middleware->handle(Object(Http\Request), 1, true)
#22 C:\xampp\htdocs\trust\system\Cookie\Guard.php(54): Cookie\Queue->handle(Object(Http\Request), 1, true)
#23 C:\xampp\htdocs\trust\vendor\stack\builder\src\Stack\StackedHttpKernel.php(23): Cookie\Guard->handle(Object(Http\Request), 1, true)
#24 C:\xampp\htdocs\trust\system\Foundation\Application.php(615): Stack\StackedHttpKernel->handle(Object(Http\Request))
#25 C:\xampp\htdocs\trust\app\Boot\Start.php(244): Foundation\Application->run()
#26 C:\xampp\htdocs\trust\public\index.php(37): require('C:\\xampp\\htdocs...')
#27 {main} [] []
[2016-11-04 13:57:28] production.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected ''.jpg'' (T_CONSTANT_ENCAPSED_STRING)' in C:\xampp\htdocs\trust\app\Views\Welcome\Service.php:9
Stack trace:
#0 [internal function]: Exception\Handler->handleShutdown()
#1 {main} [] []
[2016-11-04 13:58:47] production.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected ''.jpg'' (T_CONSTANT_ENCAPSED_STRING)' in C:\xampp\htdocs\trust\app\Views\Welcome\Service.php:10
Stack trace:
#0 [internal function]: Exception\Handler->handleShutdown()
#1 {main} [] []
[2016-11-04 13:59:11] production.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected ''.jpg'' (T_CONSTANT_ENCAPSED_STRING)' in C:\xampp\htdocs\trust\app\Views\Welcome\Service.php:10
Stack trace:
#0 [internal function]: Exception\Handler->handleShutdown()
#1 {main} [] []
[2016-11-04 13:59:34] production.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected ''.jpg'' (T_CONSTANT_ENCAPSED_STRING)' in C:\xampp\htdocs\trust\app\Views\Welcome\Service.php:10
Stack trace:
#0 [internal function]: Exception\Handler->handleShutdown()
#1 {main} [] []
[2016-11-04 14:38:57] production.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected 'return' (T_RETURN)' in C:\xampp\htdocs\trust\app\Controllers\Welcome.php:61
Stack trace:
#0 [internal function]: Exception\Handler->handleShutdown()
#1 {main} [] []
[2016-11-04 16:04:32] production.ERROR: exception 'ErrorException' with message 'Undefined offset: 0' in C:\xampp\htdocs\trust\app\Controllers\Admin\Family.php:42
Stack trace:
#0 C:\xampp\htdocs\trust\app\Controllers\Admin\Family.php(42): Exception\Handler->handleError(8, 'Undefined offse...', 'C:\\xampp\\htdocs...', 42, Array)
#1 [internal function]: App\Controllers\Admin\Family->index()
#2 C:\xampp\htdocs\trust\system\Routing\Controller.php(240): call_user_func_array(Array, Array)
#3 C:\xampp\htdocs\trust\system\Routing\ControllerDispatcher.php(91): Routing\Controller->callAction('index', Array)
#4 C:\xampp\htdocs\trust\system\Routing\ControllerDispatcher.php(60): Routing\ControllerDispatcher->call(Object(App\Controllers\Admin\Family), Object(Routing\Route), 'index')
#5 C:\xampp\htdocs\trust\system\Routing\Router.php(958): Routing\ControllerDispatcher->dispatch(Object(Routing\Route), Object(Http\Request), 'App\\Controllers...', 'index')
#6 [internal function]: Routing\Router->Routing\{closure}()
#7 C:\xampp\htdocs\trust\system\Routing\Route.php(128): call_user_func_array(Object(Closure), Array)
#8 C:\xampp\htdocs\trust\system\Routing\Router.php(1026): Routing\Route->run()
#9 C:\xampp\htdocs\trust\system\Routing\Router.php(994): Routing\Router->dispatchToRoute(Object(Http\Request))
#10 C:\xampp\htdocs\trust\system\Foundation\Application.php(744): Routing\Router->dispatch(Object(Http\Request))
#11 C:\xampp\htdocs\trust\system\Foundation\Application.php(717): Foundation\Application->dispatch(Object(Http\Request))
#12 C:\xampp\htdocs\trust\shared\Http\ContentGuard.php(62): Foundation\Application->handle(Object(Http\Request), 1, true)
#13 C:\xampp\htdocs\trust\system\Session\Middleware.php(77): Shared\Http\ContentGuard->handle(Object(Http\Request), 1, true)
#14 C:\xampp\htdocs\trust\system\Cookie\Queue.php(49): Session\Middleware->handle(Object(Http\Request), 1, true)
#15 C:\xampp\htdocs\trust\system\Cookie\Guard.php(54): Cookie\Queue->handle(Object(Http\Request), 1, true)
#16 C:\xampp\htdocs\trust\vendor\stack\builder\src\Stack\StackedHttpKernel.php(23): Cookie\Guard->handle(Object(Http\Request), 1, true)
#17 C:\xampp\htdocs\trust\system\Foundation\Application.php(615): Stack\StackedHttpKernel->handle(Object(Http\Request))
#18 C:\xampp\htdocs\trust\app\Boot\Start.php(244): Foundation\Application->run()
#19 C:\xampp\htdocs\trust\public\index.php(37): require('C:\\xampp\\htdocs...')
#20 {main} [] []
[2016-11-04 16:08:48] production.ERROR: exception 'ErrorException' with message 'Undefined offset: 0' in C:\xampp\htdocs\trust\app\Controllers\Admin\Family.php:42
Stack trace:
#0 C:\xampp\htdocs\trust\app\Controllers\Admin\Family.php(42): Exception\Handler->handleError(8, 'Undefined offse...', 'C:\\xampp\\htdocs...', 42, Array)
#1 [internal function]: App\Controllers\Admin\Family->index()
#2 C:\xampp\htdocs\trust\system\Routing\Controller.php(240): call_user_func_array(Array, Array)
#3 C:\xampp\htdocs\trust\system\Routing\ControllerDispatcher.php(91): Routing\Controller->callAction('index', Array)
#4 C:\xampp\htdocs\trust\system\Routing\ControllerDispatcher.php(60): Routing\ControllerDispatcher->call(Object(App\Controllers\Admin\Family), Object(Routing\Route), 'index')
#5 C:\xampp\htdocs\trust\system\Routing\Router.php(958): Routing\ControllerDispatcher->dispatch(Object(Routing\Route), Object(Http\Request), 'App\\Controllers...', 'index')
#6 [internal function]: Routing\Router->Routing\{closure}()
#7 C:\xampp\htdocs\trust\system\Routing\Route.php(128): call_user_func_array(Object(Closure), Array)
#8 C:\xampp\htdocs\trust\system\Routing\Router.php(1026): Routing\Route->run()
#9 C:\xampp\htdocs\trust\system\Routing\Router.php(994): Routing\Router->dispatchToRoute(Object(Http\Request))
#10 C:\xampp\htdocs\trust\system\Foundation\Application.php(744): Routing\Router->dispatch(Object(Http\Request))
#11 C:\xampp\htdocs\trust\system\Foundation\Application.php(717): Foundation\Application->dispatch(Object(Http\Request))
#12 C:\xampp\htdocs\trust\shared\Http\ContentGuard.php(62): Foundation\Application->handle(Object(Http\Request), 1, true)
#13 C:\xampp\htdocs\trust\system\Session\Middleware.php(77): Shared\Http\ContentGuard->handle(Object(Http\Request), 1, true)
#14 C:\xampp\htdocs\trust\system\Cookie\Queue.php(49): Session\Middleware->handle(Object(Http\Request), 1, true)
#15 C:\xampp\htdocs\trust\system\Cookie\Guard.php(54): Cookie\Queue->handle(Object(Http\Request), 1, true)
#16 C:\xampp\htdocs\trust\vendor\stack\builder\src\Stack\StackedHttpKernel.php(23): Cookie\Guard->handle(Object(Http\Request), 1, true)
#17 C:\xampp\htdocs\trust\system\Foundation\Application.php(615): Stack\StackedHttpKernel->handle(Object(Http\Request))
#18 C:\xampp\htdocs\trust\app\Boot\Start.php(244): Foundation\Application->run()
#19 C:\xampp\htdocs\trust\public\index.php(37): require('C:\\xampp\\htdocs...')
#20 {main} [] []
[2016-11-04 16:13:16] production.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected ')'' in C:\xampp\htdocs\trust\app\Templates\AdminLte\backend.php:169
Stack trace:
#0 [internal function]: Exception\Handler->handleShutdown()
#1 {main} [] []
[2016-11-04 16:14:58] production.ERROR: exception 'ErrorException' with message 'Trying to get property of non-object' in C:\xampp\htdocs\trust\app\Templates\AdminLte\backend.php:252
Stack trace:
#0 C:\xampp\htdocs\trust\app\Templates\AdminLte\backend.php(252): Exception\Handler->handleError(8, 'Trying to get p...', 'C:\\xampp\\htdocs...', 252, Array)
#1 C:\xampp\htdocs\trust\system\View\Engines\PhpEngine.php(56): include('C:\\xampp\\htdocs...')
#2 C:\xampp\htdocs\trust\system\View\Engines\PhpEngine.php(31): View\Engines\PhpEngine->evaluatePath('C:\\xampp\\htdocs...', Array)
#3 C:\xampp\htdocs\trust\system\View\View.php(96): View\Engines\PhpEngine->get('C:\\xampp\\htdocs...', Array)
#4 C:\xampp\htdocs\trust\system\View\View.php(82): View\View->renderContents()
#5 C:\xampp\htdocs\trust\app\Core\Controller.php(70): View\View->render()
#6 C:\xampp\htdocs\trust\system\Routing\Controller.php(250): App\Core\Controller->processResponse(Object(View\View))
#7 C:\xampp\htdocs\trust\system\Routing\ControllerDispatcher.php(91): Routing\Controller->callAction('index', Array)
#8 C:\xampp\htdocs\trust\system\Routing\ControllerDispatcher.php(60): Routing\ControllerDispatcher->call(Object(App\Controllers\Admin\Dashboard), Object(Routing\Route), 'index')
#9 C:\xampp\htdocs\trust\system\Routing\Router.php(958): Routing\ControllerDispatcher->dispatch(Object(Routing\Route), Object(Http\Request), 'App\\Controllers...', 'index')
#10 [internal function]: Routing\Router->Routing\{closure}()
#11 C:\xampp\htdocs\trust\system\Routing\Route.php(128): call_user_func_array(Object(Closure), Array)
#12 C:\xampp\htdocs\trust\system\Routing\Router.php(1026): Routing\Route->run()
#13 C:\xampp\htdocs\trust\system\Routing\Router.php(994): Routing\Router->dispatchToRoute(Object(Http\Request))
#14 C:\xampp\htdocs\trust\system\Foundation\Application.php(744): Routing\Router->dispatch(Object(Http\Request))
#15 C:\xampp\htdocs\trust\system\Foundation\Application.php(717): Foundation\Application->dispatch(Object(Http\Request))
#16 C:\xampp\htdocs\trust\shared\Http\ContentGuard.php(62): Foundation\Application->handle(Object(Http\Request), 1, true)
#17 C:\xampp\htdocs\trust\system\Session\Middleware.php(77): Shared\Http\ContentGuard->handle(Object(Http\Request), 1, true)
#18 C:\xampp\htdocs\trust\system\Cookie\Queue.php(49): Session\Middleware->handle(Object(Http\Request), 1, true)
#19 C:\xampp\htdocs\trust\system\Cookie\Guard.php(54): Cookie\Queue->handle(Object(Http\Request), 1, true)
#20 C:\xampp\htdocs\trust\vendor\stack\builder\src\Stack\StackedHttpKernel.php(23): Cookie\Guard->handle(Object(Http\Request), 1, true)
#21 C:\xampp\htdocs\trust\system\Foundation\Application.php(615): Stack\StackedHttpKernel->handle(Object(Http\Request))
#22 C:\xampp\htdocs\trust\app\Boot\Start.php(244): Foundation\Application->run()
#23 C:\xampp\htdocs\trust\public\index.php(37): require('C:\\xampp\\htdocs...')
#24 {main} [] []
[2016-11-04 16:41:38] production.ERROR: exception 'ErrorException' with message 'Undefined offset: 0' in C:\xampp\htdocs\trust\app\Controllers\Admin\Family.php:42
Stack trace:
#0 C:\xampp\htdocs\trust\app\Controllers\Admin\Family.php(42): Exception\Handler->handleError(8, 'Undefined offse...', 'C:\\xampp\\htdocs...', 42, Array)
#1 [internal function]: App\Controllers\Admin\Family->index()
#2 C:\xampp\htdocs\trust\system\Routing\Controller.php(240): call_user_func_array(Array, Array)
#3 C:\xampp\htdocs\trust\system\Routing\ControllerDispatcher.php(91): Routing\Controller->callAction('index', Array)
#4 C:\xampp\htdocs\trust\system\Routing\ControllerDispatcher.php(60): Routing\ControllerDispatcher->call(Object(App\Controllers\Admin\Family), Object(Routing\Route), 'index')
#5 C:\xampp\htdocs\trust\system\Routing\Router.php(958): Routing\ControllerDispatcher->dispatch(Object(Routing\Route), Object(Http\Request), 'App\\Controllers...', 'index')
#6 [internal function]: Routing\Router->Routing\{closure}()
#7 C:\xampp\htdocs\trust\system\Routing\Route.php(128): call_user_func_array(Object(Closure), Array)
#8 C:\xampp\htdocs\trust\system\Routing\Router.php(1026): Routing\Route->run()
#9 C:\xampp\htdocs\trust\system\Routing\Router.php(994): Routing\Router->dispatchToRoute(Object(Http\Request))
#10 C:\xampp\htdocs\trust\system\Foundation\Application.php(744): Routing\Router->dispatch(Object(Http\Request))
#11 C:\xampp\htdocs\trust\system\Foundation\Application.php(717): Foundation\Application->dispatch(Object(Http\Request))
#12 C:\xampp\htdocs\trust\shared\Http\ContentGuard.php(62): Foundation\Application->handle(Object(Http\Request), 1, true)
#13 C:\xampp\htdocs\trust\system\Session\Middleware.php(77): Shared\Http\ContentGuard->handle(Object(Http\Request), 1, true)
#14 C:\xampp\htdocs\trust\system\Cookie\Queue.php(49): Session\Middleware->handle(Object(Http\Request), 1, true)
#15 C:\xampp\htdocs\trust\system\Cookie\Guard.php(54): Cookie\Queue->handle(Object(Http\Request), 1, true)
#16 C:\xampp\htdocs\trust\vendor\stack\builder\src\Stack\StackedHttpKernel.php(23): Cookie\Guard->handle(Object(Http\Request), 1, true)
#17 C:\xampp\htdocs\trust\system\Foundation\Application.php(615): Stack\StackedHttpKernel->handle(Object(Http\Request))
#18 C:\xampp\htdocs\trust\app\Boot\Start.php(244): Foundation\Application->run()
#19 C:\xampp\htdocs\trust\public\index.php(37): require('C:\\xampp\\htdocs...')
#20 {main} [] []
[2016-11-04 17:07:45] production.ERROR: exception 'ErrorException' with message 'Undefined offset: 0' in C:\xampp\htdocs\trust\app\Controllers\Admin\Family.php:42
Stack trace:
#0 C:\xampp\htdocs\trust\app\Controllers\Admin\Family.php(42): Exception\Handler->handleError(8, 'Undefined offse...', 'C:\\xampp\\htdocs...', 42, Array)
#1 [internal function]: App\Controllers\Admin\Family->index()
#2 C:\xampp\htdocs\trust\system\Routing\Controller.php(240): call_user_func_array(Array, Array)
#3 C:\xampp\htdocs\trust\system\Routing\ControllerDispatcher.php(91): Routing\Controller->callAction('index', Array)
#4 C:\xampp\htdocs\trust\system\Routing\ControllerDispatcher.php(60): Routing\ControllerDispatcher->call(Object(App\Controllers\Admin\Family), Object(Routing\Route), 'index')
#5 C:\xampp\htdocs\trust\system\Routing\Router.php(958): Routing\ControllerDispatcher->dispatch(Object(Routing\Route), Object(Http\Request), 'App\\Controllers...', 'index')
#6 [internal function]: Routing\Router->Routing\{closure}()
#7 C:\xampp\htdocs\trust\system\Routing\Route.php(128): call_user_func_array(Object(Closure), Array)
#8 C:\xampp\htdocs\trust\system\Routing\Router.php(1026): Routing\Route->run()
#9 C:\xampp\htdocs\trust\system\Routing\Router.php(994): Routing\Router->dispatchToRoute(Object(Http\Request))
#10 C:\xampp\htdocs\trust\system\Foundation\Application.php(744): Routing\Router->dispatch(Object(Http\Request))
#11 C:\xampp\htdocs\trust\system\Foundation\Application.php(717): Foundation\Application->dispatch(Object(Http\Request))
#12 C:\xampp\htdocs\trust\shared\Http\ContentGuard.php(62): Foundation\Application->handle(Object(Http\Request), 1, true)
#13 C:\xampp\htdocs\trust\system\Session\Middleware.php(77): Shared\Http\ContentGuard->handle(Object(Http\Request), 1, true)
#14 C:\xampp\htdocs\trust\system\Cookie\Queue.php(49): Session\Middleware->handle(Object(Http\Request), 1, true)
#15 C:\xampp\htdocs\trust\system\Cookie\Guard.php(54): Cookie\Queue->handle(Object(Http\Request), 1, true)
#16 C:\xampp\htdocs\trust\vendor\stack\builder\src\Stack\StackedHttpKernel.php(23): Cookie\Guard->handle(Object(Http\Request), 1, true)
#17 C:\xampp\htdocs\trust\system\Foundation\Application.php(615): Stack\StackedHttpKernel->handle(Object(Http\Request))
#18 C:\xampp\htdocs\trust\app\Boot\Start.php(244): Foundation\Application->run()
#19 C:\xampp\htdocs\trust\public\index.php(37): require('C:\\xampp\\htdocs...')
#20 {main} [] []
[2016-11-04 17:24:50] production.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Class 'App\Controllers\Admin\AnotherClass' not found' in C:\xampp\htdocs\trust\app\Controllers\Admin\My.php:17
Stack trace:
#0 [internal function]: Exception\Handler->handleShutdown()
#1 {main} [] []
[2016-11-04 17:33:20] production.ERROR: exception 'ErrorException' with message 'Trying to get property of non-object' in C:\xampp\htdocs\trust\app\Views\Admin\My\index.php:20
Stack trace:
#0 C:\xampp\htdocs\trust\app\Views\Admin\My\index.php(20): Exception\Handler->handleError(8, 'Trying to get p...', 'C:\\xampp\\htdocs...', 20, Array)
#1 C:\xampp\htdocs\trust\system\View\Engines\PhpEngine.php(56): include('C:\\xampp\\htdocs...')
#2 C:\xampp\htdocs\trust\system\View\Engines\PhpEngine.php(31): View\Engines\PhpEngine->evaluatePath('C:\\xampp\\htdocs...', Array)
#3 C:\xampp\htdocs\trust\system\View\View.php(96): View\Engines\PhpEngine->get('C:\\xampp\\htdocs...', Array)
#4 C:\xampp\htdocs\trust\system\View\View.php(82): View\View->renderContents()
#5 C:\xampp\htdocs\trust\system\View\View.php(111): View\View->render()
#6 C:\xampp\htdocs\trust\system\View\View.php(96): View\View->gatherData()
#7 C:\xampp\htdocs\trust\system\View\View.php(82): View\View->renderContents()
#8 C:\xampp\htdocs\trust\app\Core\Controller.php(70): View\View->render()
#9 C:\xampp\htdocs\trust\system\Routing\Controller.php(250): App\Core\Controller->processResponse(Object(View\View))
#10 C:\xampp\htdocs\trust\system\Routing\ControllerDispatcher.php(91): Routing\Controller->callAction('index', Array)
#11 C:\xampp\htdocs\trust\system\Routing\ControllerDispatcher.php(60): Routing\ControllerDispatcher->call(Object(App\Controllers\Admin\My), Object(Routing\Route), 'index')
#12 C:\xampp\htdocs\trust\system\Routing\Router.php(958): Routing\ControllerDispatcher->dispatch(Object(Routing\Route), Object(Http\Request), 'App\\Controllers...', 'index')
#13 [internal function]: Routing\Router->Routing\{closure}()
#14 C:\xampp\htdocs\trust\system\Routing\Route.php(128): call_user_func_array(Object(Closure), Array)
#15 C:\xampp\htdocs\trust\system\Routing\Router.php(1026): Routing\Route->run()
#16 C:\xampp\htdocs\trust\system\Routing\Router.php(994): Routing\Router->dispatchToRoute(Object(Http\Request))
#17 C:\xampp\htdocs\trust\system\Foundation\Application.php(744): Routing\Router->dispatch(Object(Http\Request))
#18 C:\xampp\htdocs\trust\system\Foundation\Application.php(717): Foundation\Application->dispatch(Object(Http\Request))
#19 C:\xampp\htdocs\trust\shared\Http\ContentGuard.php(62): Foundation\Application->handle(Object(Http\Request), 1, true)
#20 C:\xampp\htdocs\trust\system\Session\Middleware.php(77): Shared\Http\ContentGuard->handle(Object(Http\Request), 1, true)
#21 C:\xampp\htdocs\trust\system\Cookie\Queue.php(49): Session\Middleware->handle(Object(Http\Request), 1, true)
#22 C:\xampp\htdocs\trust\system\Cookie\Guard.php(54): Cookie\Queue->handle(Object(Http\Request), 1, true)
#23 C:\xampp\htdocs\trust\vendor\stack\builder\src\Stack\StackedHttpKernel.php(23): Cookie\Guard->handle(Object(Http\Request), 1, true)
#24 C:\xampp\htdocs\trust\system\Foundation\Application.php(615): Stack\StackedHttpKernel->handle(Object(Http\Request))
#25 C:\xampp\htdocs\trust\app\Boot\Start.php(244): Foundation\Application->run()
#26 C:\xampp\htdocs\trust\public\index.php(37): require('C:\\xampp\\htdocs...')
#27 {main} [] []
[2016-11-04 18:04:29] production.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Call to undefined function siteurl()' in C:\xampp\htdocs\trust\app\Views\Admin\My\index.php:32
Stack trace:
#0 [internal function]: Exception\Handler->handleShutdown()
#1 {main} [] []
[2016-11-05 04:49:42] production.ERROR: exception 'InvalidArgumentException' with message 'Unable to load the view 'Admin/Family/Index' on domain 'App'.' in /var/www/html/trust/system/View/Factory.php:280
Stack trace:
#0 /var/www/html/trust/system/View/Factory.php(76): View\Factory->find('Admin/Family/In...', NULL)
#1 [internal function]: View\Factory->make('Admin/Family/In...', Array)
#2 /var/www/html/trust/system/Support/Facades/Facade.php(111): call_user_func_array(Array, Array)
#3 /var/www/html/trust/app/Core/Controller.php(99): Support\Facades\Facade::__callStatic('make', Array)
#4 /var/www/html/trust/app/Core/Controller.php(99): Support\Facades\View::make('Admin/Family/In...', Array)
#5 /var/www/html/trust/app/Controllers/Admin/Family.php(50): App\Core\Controller->getView()
#6 [internal function]: App\Controllers\Admin\Family->index()
#7 /var/www/html/trust/system/Routing/Controller.php(240): call_user_func_array(Array, Array)
#8 /var/www/html/trust/system/Routing/ControllerDispatcher.php(91): Routing\Controller->callAction('index', Array)
#9 /var/www/html/trust/system/Routing/ControllerDispatcher.php(60): Routing\ControllerDispatcher->call(Object(App\Controllers\Admin\Family), Object(Routing\Route), 'index')
#10 /var/www/html/trust/system/Routing/Router.php(958): Routing\ControllerDispatcher->dispatch(Object(Routing\Route), Object(Http\Request), 'App\\Controllers...', 'index')
#11 [internal function]: Routing\Router->Routing\{closure}()
#12 /var/www/html/trust/system/Routing/Route.php(128): call_user_func_array(Object(Closure), Array)
#13 /var/www/html/trust/system/Routing/Router.php(1026): Routing\Route->run()
#14 /var/www/html/trust/system/Routing/Router.php(994): Routing\Router->dispatchToRoute(Object(Http\Request))
#15 /var/www/html/trust/system/Foundation/Application.php(744): Routing\Router->dispatch(Object(Http\Request))
#16 /var/www/html/trust/system/Foundation/Application.php(717): Foundation\Application->dispatch(Object(Http\Request))
#17 /var/www/html/trust/shared/Http/ContentGuard.php(62): Foundation\Application->handle(Object(Http\Request), 1, true)
#18 /var/www/html/trust/system/Session/Middleware.php(77): Shared\Http\ContentGuard->handle(Object(Http\Request), 1, true)
#19 /var/www/html/trust/system/Cookie/Queue.php(49): Session\Middleware->handle(Object(Http\Request), 1, true)
#20 /var/www/html/trust/system/Cookie/Guard.php(54): Cookie\Queue->handle(Object(Http\Request), 1, true)
#21 /var/www/html/trust/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Cookie\Guard->handle(Object(Http\Request), 1, true)
#22 /var/www/html/trust/system/Foundation/Application.php(615): Stack\StackedHttpKernel->handle(Object(Http\Request))
#23 /var/www/html/trust/app/Boot/Start.php(244): Foundation\Application->run()
#24 /var/www/html/trust/public/index.php(37): require('/var/www/html/t...')
#25 {main} [] []
[2016-11-05 04:51:14] production.ERROR: exception 'InvalidArgumentException' with message 'Unable to load the view 'Admin/Family/Index' on domain 'App'.' in /var/www/html/trust/system/View/Factory.php:280
Stack trace:
#0 /var/www/html/trust/system/View/Factory.php(76): View\Factory->find('Admin/Family/In...', NULL)
#1 [internal function]: View\Factory->make('Admin/Family/In...', Array)
#2 /var/www/html/trust/system/Support/Facades/Facade.php(111): call_user_func_array(Array, Array)
#3 /var/www/html/trust/app/Core/Controller.php(99): Support\Facades\Facade::__callStatic('make', Array)
#4 /var/www/html/trust/app/Core/Controller.php(99): Support\Facades\View::make('Admin/Family/In...', Array)
#5 /var/www/html/trust/app/Controllers/Admin/Family.php(50): App\Core\Controller->getView()
#6 [internal function]: App\Controllers\Admin\Family->index()
#7 /var/www/html/trust/system/Routing/Controller.php(240): call_user_func_array(Array, Array)
#8 /var/www/html/trust/system/Routing/ControllerDispatcher.php(91): Routing\Controller->callAction('index', Array)
#9 /var/www/html/trust/system/Routing/ControllerDispatcher.php(60): Routing\ControllerDispatcher->call(Object(App\Controllers\Admin\Family), Object(Routing\Route), 'index')
#10 /var/www/html/trust/system/Routing/Router.php(958): Routing\ControllerDispatcher->dispatch(Object(Routing\Route), Object(Http\Request), 'App\\Controllers...', 'index')
#11 [internal function]: Routing\Router->Routing\{closure}()
#12 /var/www/html/trust/system/Routing/Route.php(128): call_user_func_array(Object(Closure), Array)
#13 /var/www/html/trust/system/Routing/Router.php(1026): Routing\Route->run()
#14 /var/www/html/trust/system/Routing/Router.php(994): Routing\Router->dispatchToRoute(Object(Http\Request))
#15 /var/www/html/trust/system/Foundation/Application.php(744): Routing\Router->dispatch(Object(Http\Request))
#16 /var/www/html/trust/system/Foundation/Application.php(717): Foundation\Application->dispatch(Object(Http\Request))
#17 /var/www/html/trust/shared/Http/ContentGuard.php(62): Foundation\Application->handle(Object(Http\Request), 1, true)
#18 /var/www/html/trust/system/Session/Middleware.php(77): Shared\Http\ContentGuard->handle(Object(Http\Request), 1, true)
#19 /var/www/html/trust/system/Cookie/Queue.php(49): Session\Middleware->handle(Object(Http\Request), 1, true)
#20 /var/www/html/trust/system/Cookie/Guard.php(54): Cookie\Queue->handle(Object(Http\Request), 1, true)
#21 /var/www/html/trust/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Cookie\Guard->handle(Object(Http\Request), 1, true)
#22 /var/www/html/trust/system/Foundation/Application.php(615): Stack\StackedHttpKernel->handle(Object(Http\Request))
#23 /var/www/html/trust/app/Boot/Start.php(244): Foundation\Application->run()
#24 /var/www/html/trust/public/index.php(37): require('/var/www/html/t...')
#25 {main} [] []
